#!/usr/bin/env python3
"""
Script to add more questions - Module 1 (271-371) completing Module 1
"""

import asyncio
import uuid
from motor.motor_asyncio import AsyncIOMotorClient
import os
from dotenv import load_dotenv

load_dotenv()

# More questions from Module 1 (271-371)
NEW_QUESTIONS = [
    {"modulo": "1", "numero": "271", "questao": "Por que a sinalização deve ser uniforme em todo o país?", "alternativas": {"A": "Para que uma mesma placa signifique a mesma ação em qualquer cidade, aumentando a previsibilidade.", "B": "Para permitir variações locais frequentes.", "C": "Para confundir visitantes.", "D": "Para favorecer o design regional."}, "resposta": "A", "comentario": "Uniformidade garante que motoristas compreendam sinais independentemente do local."},
    {"modulo": "1", "numero": "272", "questao": "Como a sinalização horizontal complementa a vertical quando há conflito entre elas?", "alternativas": {"A": "A hierarquia define prioridade; marcas no solo orientam movimentos e, se houver conflito, segue-se a ordem legal.", "B": "A sinalização horizontal sempre prevalece.", "C": "A sinalização vertical sempre prevalece.", "D": "Conflitos não ocorrem entre sinalizações."}, "resposta": "A", "comentario": "Em conflitos, é preciso considerar a hierarquia: agente, semáforo, placas, marcas no solo."},
    {"modulo": "1", "numero": "273", "questao": "Considerando direção defensiva, qual é a relação entre atenção, distância e antecipação?", "alternativas": {"A": "Atenção constante e manter distância permitem antecipar ações de outros e evitar sinistros.", "B": "Atenção é menos importante que velocidade.", "C": "Distância não influencia na antecipação.", "D": "Antecipação substitui atenção."}, "resposta": "A", "comentario": "A combinação dos três cria o escudo da direção defensiva, reduzindo riscos."},
    {"modulo": "1", "numero": "274", "questao": "Ao ver uma linha contínua amarela simples no centro da via, o que o condutor deve entender?", "alternativas": {"A": "É proibido ultrapassar naquele trecho.", "B": "A via é preferencial.", "C": "Pode ultrapassar com cuidado.", "D": "É uma faixa exclusiva de ônibus."}, "resposta": "A", "comentario": "Linha amarela contínua indica proibição de ultrapassagem por motivos de segurança e visibilidade."},
    {"modulo": "1", "numero": "275", "questao": "Quando há duas linhas amarelas contínuas lado a lado, o que isso significa?", "alternativas": {"A": "A ultrapassagem é proibida para os dois sentidos.", "B": "Somente um lado pode ultrapassar.", "C": "É uma pista de aceleração.", "D": "É uma marcação de estacionamento."}, "resposta": "A", "comentario": "Linhas duplas contínuas proíbem ultrapassagem para ambos os sentidos da via."},
    {"modulo": "1", "numero": "276", "questao": "Ao encontrar uma linha seccionada (tracejada) no centro da pista, o motorista pode:", "alternativas": {"A": "Ultrapassar com segurança, se as condições permitirem.", "B": "Parar sobre a linha.", "C": "Transitar entre as faixas livremente.", "D": "Fazer retorno em qualquer ponto."}, "resposta": "A", "comentario": "A linha seccionada permite ultrapassagem quando há segurança e boa visibilidade."},
    {"modulo": "1", "numero": "277", "questao": "O que o motorista deve fazer ao ver faixas zebradas pintadas no chão?", "alternativas": {"A": "Evitar parar ou estacionar sobre elas.", "B": "Atravessar nelas para ganhar tempo.", "C": "Usar como área de espera.", "D": "Parar para desembarque."}, "resposta": "A", "comentario": "As zebras são áreas de segurança e não devem ser ocupadas por veículos."},
    {"modulo": "1", "numero": "278", "questao": "Qual o comportamento correto ao ver uma faixa contínua branca separando faixas no mesmo sentido?", "alternativas": {"A": "Manter-se na faixa, sem mudar de pista.", "B": "Trocar de faixa rapidamente.", "C": "Ultrapassar o veículo à frente.", "D": "Estacionar no acostamento."}, "resposta": "A", "comentario": "Linha branca contínua indica proibição de mudança de faixa no mesmo sentido."},
    {"modulo": "1", "numero": "279", "questao": "Em uma via com faixas tracejadas brancas, o que o condutor pode fazer?", "alternativas": {"A": "Mudar de faixa, desde que com segurança.", "B": "Parar sobre as linhas.", "C": "Fazer retorno.", "D": "Transitar sobre o canteiro."}, "resposta": "A", "comentario": "As linhas brancas seccionadas permitem mudança de faixa em segurança."},
    {"modulo": "1", "numero": "280", "questao": "O que indica uma faixa de retenção antes de um semáforo?", "alternativas": {"A": "Ponto onde o veículo deve parar quando o sinal estiver vermelho.", "B": "Local para pedestres atravessarem.", "C": "Faixa exclusiva para motos.", "D": "Local de aceleração."}, "resposta": "A", "comentario": "A faixa de retenção indica o limite de parada nos cruzamentos."},
    {"modulo": "1", "numero": "281", "questao": "Quando há uma faixa de pedestres após a faixa de retenção, o que o condutor deve fazer?", "alternativas": {"A": "Parar antes da faixa de pedestres.", "B": "Parar sobre a faixa.", "C": "Avançar lentamente sobre ela.", "D": "Acelerar para passar antes do pedestre."}, "resposta": "A", "comentario": "A parada deve ser antes da faixa, preservando o espaço do pedestre."},
    {"modulo": "1", "numero": "282", "questao": "O que significam as setas pintadas no pavimento?", "alternativas": {"A": "Indicam o sentido ou obrigatoriedade de direção.", "B": "Enfeitam o pavimento.", "C": "Mostram que a via é de pedágio.", "D": "Avisam sobre obras próximas."}, "resposta": "A", "comentario": "As setas são orientações de direção obrigatória ou recomendada."},
    {"modulo": "1", "numero": "283", "questao": "O que indica a marcação de canalização (faixas em V ou diagonais)?", "alternativas": {"A": "Área proibida para tráfego de veículos.", "B": "Local seguro para estacionar.", "C": "Faixa de ultrapassagem.", "D": "Trecho de conversão."}, "resposta": "A", "comentario": "Canalizações organizam fluxos e devem ser respeitadas como áreas não transitáveis."},
    {"modulo": "1", "numero": "284", "questao": "Por que o condutor deve evitar circular sobre as marcas de canalização?", "alternativas": {"A": "Porque são áreas de separação de fluxos e não de circulação.", "B": "Porque podem danificar os pneus.", "C": "Porque reduzem o atrito.", "D": "Porque indicam locais de estacionamento."}, "resposta": "A", "comentario": "Essas marcas delimitam espaços sem circulação — ignorá-las é infração."},
    {"modulo": "1", "numero": "285", "questao": "O que a linha de bordo amarela pode indicar?", "alternativas": {"A": "Proibição de parada e estacionamento.", "B": "Local de ultrapassagem permitida.", "C": "Zona escolar.", "D": "Faixa de ônibus."}, "resposta": "A", "comentario": "Linha amarela no bordo da via sinaliza proibição de parada."},
    {"modulo": "1", "numero": "286", "questao": "O que o condutor pode fazer ao perceber uma faixa contínua amarela se transformando em tracejada?", "alternativas": {"A": "A partir dali, a ultrapassagem passa a ser permitida.", "B": "A ultrapassagem continua proibida.", "C": "É área escolar.", "D": "Deve estacionar o veículo."}, "resposta": "A", "comentario": "A linha tracejada sinaliza início de trecho onde a ultrapassagem é possível."},
    {"modulo": "1", "numero": "287", "questao": "Em uma curva, por que costuma haver linha contínua?", "alternativas": {"A": "Porque a visibilidade é reduzida e é proibido ultrapassar.", "B": "Porque é uma área de estacionamento.", "C": "Porque facilita ultrapassar rápido.", "D": "Porque não há necessidade de sinalização."}, "resposta": "A", "comentario": "Linha contínua reforça o perigo de ultrapassar em locais sem visibilidade."},
    {"modulo": "1", "numero": "288", "questao": "Ao ver placa com pictograma em forma de Y, o que isso significa?", "alternativas": {"A": "Divisão de pistas — escolha o sentido antes do ponto.", "B": "Retorno obrigatório.", "C": "Local de ultrapassagem.", "D": "Área de estacionamento."}, "resposta": "A", "comentario": "O formato em Y alerta sobre divisão de fluxo, e o motorista deve escolher o sentido correto."},
    {"modulo": "1", "numero": "289", "questao": "O que o condutor deve fazer ao se aproximar de uma área zebrada entre faixas?", "alternativas": {"A": "Evitar circular ou parar sobre a área zebrada.", "B": "Aproveitar para ultrapassar.", "C": "Usar para conversão rápida.", "D": "Estacionar brevemente."}, "resposta": "A", "comentario": "A zebrada é área de separação de fluxos e não deve ser ocupada."},
    {"modulo": "1", "numero": "290", "questao": "Por que as linhas horizontais ajudam a fluidez do trânsito?", "alternativas": {"A": "Porque orientam condutores e reduzem dúvidas sobre posicionamento e manobras.", "B": "Porque substituem os semáforos.", "C": "Porque permitem estacionar onde quiser.", "D": "Porque reduzem o limite de velocidade."}, "resposta": "A", "comentario": "A sinalização horizontal mantém o fluxo ordenado e previsível."},
    {"modulo": "1", "numero": "291", "questao": "Ao transitar em pista com setas de conversão à esquerda e em frente, o que o motorista pode fazer?", "alternativas": {"A": "Escolher entre seguir em frente ou virar à esquerda.", "B": "Fazer retorno no local.", "C": "Estacionar para esperar.", "D": "Virar à direita."}, "resposta": "A", "comentario": "As setas informam as direções permitidas, e o condutor deve se posicionar conforme a intenção."},
    {"modulo": "1", "numero": "292", "questao": "Se uma faixa exclusiva de ônibus é delimitada por linha contínua, o que isso indica?", "alternativas": {"A": "É proibido transitar ou cruzar a faixa.", "B": "Pode cruzar rapidamente.", "C": "Pode estacionar brevemente.", "D": "Pode usar para conversão."}, "resposta": "A", "comentario": "Linha contínua indica proibição total de cruzar a faixa exclusiva."},
    {"modulo": "1", "numero": "293", "questao": "O que o condutor deve fazer ao ver setas de convergência (duas setas unindo-se)?", "alternativas": {"A": "Reduzir e preparar-se para junção de faixas.", "B": "Acelerar para passar primeiro.", "C": "Parar no meio da pista.", "D": "Mudar de sentido."}, "resposta": "A", "comentario": "Setas de convergência alertam para redução e atenção à fusão de tráfego."},
    {"modulo": "1", "numero": "304", "questao": "Se o motorista encontra faixas de pedestres em série, o que isso indica?", "alternativas": {"A": "Zona com travessia frequente, exigindo atenção constante.", "B": "Local de estacionamento.", "C": "Área de carga e descarga.", "D": "Cruzamento preferencial."}, "resposta": "A", "comentario": "A repetição de faixas sinaliza alto fluxo de pedestres — atenção redobrada."},
    {"modulo": "1", "numero": "305", "questao": "Em vias com setas de retorno pintadas no solo, o que deve fazer o motorista?", "alternativas": {"A": "Fazer o retorno apenas naquele ponto indicado.", "B": "Fazer o retorno onde preferir.", "C": "Ignorar a seta.", "D": "Fazer ultrapassagem."}, "resposta": "A", "comentario": "As setas delimitam o ponto autorizado para retorno, garantindo segurança."},
    {"modulo": "1", "numero": "306", "questao": "Qual o comportamento correto ao aproximar-se de linhas duplas, sendo uma contínua e outra tracejada?", "alternativas": {"A": "Apenas o lado da linha tracejada pode ultrapassar.", "B": "A ultrapassagem é proibida para ambos.", "C": "Os dois lados podem ultrapassar.", "D": "É faixa de pedestres."}, "resposta": "A", "comentario": "O lado tracejado indica onde é permitido ultrapassar — o contínuo, não."},
    {"modulo": "1", "numero": "307", "questao": "O que a linha de canalização entre faixas de conversão representa?", "alternativas": {"A": "Espaço que separa fluxos diferentes e não pode ser ocupado.", "B": "Local de ultrapassagem.", "C": "Trecho de estacionamento.", "D": "Área de pedágio."}, "resposta": "A", "comentario": "Canalização organiza o fluxo e proíbe circulação sobre ela."},
    {"modulo": "1", "numero": "308", "questao": "Por que a linha de bordo é importante em vias estreitas?", "alternativas": {"A": "Ajuda o condutor a manter o veículo corretamente posicionado na pista.", "B": "Serve apenas para ciclistas.", "C": "Indica local de pedágio.", "D": "Substitui a iluminação pública."}, "resposta": "A", "comentario": "Linha de bordo auxilia o posicionamento seguro, principalmente à noite."},
    {"modulo": "1", "numero": "309", "questao": "O que o condutor deve evitar fazer em uma interseção com marcas de cruzamento pintadas em X?", "alternativas": {"A": "Parar sobre a área demarcada.", "B": "Aguardar para avançar.", "C": "Entrar mesmo com o cruzamento cheio.", "D": "Avançar o sinal vermelho."}, "resposta": "A", "comentario": "Essas marcas indicam área de não bloqueio — o veículo não deve parar sobre o X."},
    {"modulo": "1", "numero": "310", "questao": "Por que a sinalização horizontal é considerada um complemento vital da vertical?", "alternativas": {"A": "Porque reforça mensagens diretamente no campo de visão do condutor.", "B": "Porque substitui todas as placas.", "C": "Porque é opcional em rodovias.", "D": "Porque só serve de enfeite."}, "resposta": "A", "comentario": "As duas trabalham em conjunto — a vertical informa, a horizontal reforça visualmente."},
    {"modulo": "1", "numero": "311", "questao": "Como o condutor deve agir em uma via onde há marcações de canalização danificadas ou apagadas?", "alternativas": {"A": "Redobrar a atenção e seguir o fluxo, sem invadir áreas incertas.", "B": "Ignorar completamente a sinalização.", "C": "Usar o acostamento.", "D": "Seguir os outros veículos cegamente."}, "resposta": "A", "comentario": "Mesmo com sinalização apagada, o motorista deve agir com cautela e prever limites de circulação."},
    {"modulo": "1", "numero": "312", "questao": "Por que as linhas seccionadas são mais usadas em retas do que em curvas?", "alternativas": {"A": "Porque nas retas há visibilidade suficiente para ultrapassagem segura.", "B": "Porque nas curvas é mais bonito.", "C": "Porque são mais fáceis de pintar.", "D": "Porque reduzem custos."}, "resposta": "A", "comentario": "Nas curvas, a visibilidade reduzida exige linha contínua — nas retas, a tracejada é segura."},
    {"modulo": "1", "numero": "313", "questao": "As placas de indicação servem principalmente para:", "alternativas": {"A": "Informar direções, destinos e serviços disponíveis.", "B": "Proibir manobras perigosas.", "C": "Alertar sobre riscos na pista.", "D": "Indicar infrações de trânsito."}, "resposta": "A", "comentario": "Placas de indicação têm função informativa e orientadora."},
    {"modulo": "1", "numero": "314", "questao": "Qual é a cor predominante das placas de indicação de destinos e direções em rodovias?", "alternativas": {"A": "Verde.", "B": "Vermelha.", "C": "Amarela.", "D": "Azul."}, "resposta": "A", "comentario": "Placas verdes orientam sobre cidades, distâncias e direções."},
    {"modulo": "1", "numero": "315", "questao": "Em área urbana, uma placa azul com o símbolo de uma cruz vermelha indica:", "alternativas": {"A": "A presença de um serviço de saúde nas proximidades.", "B": "Que é proibido estacionar.", "C": "Que há escola por perto.", "D": "Um ponto turístico."}, "resposta": "A", "comentario": "Placas azuis identificam serviços públicos, como hospitais."},
    {"modulo": "1", "numero": "316", "questao": "Uma placa marrom com o símbolo de uma cachoeira indica:", "alternativas": {"A": "Um atrativo turístico ou ponto de interesse.", "B": "Um risco de inundação.", "C": "A presença de obras na via.", "D": "Um serviço de emergência."}, "resposta": "A", "comentario": "Placas marrons têm função turística."},
    {"modulo": "1", "numero": "317", "questao": "O que o motorista entende ao ver uma placa azul com o símbolo de um telefone?", "alternativas": {"A": "Há telefone público disponível.", "B": "É obrigatório ligar para o Detran.", "C": "A via tem pedágio.", "D": "Há um posto de gasolina."}, "resposta": "A", "comentario": "Placas azuis informam serviços úteis."},
    {"modulo": "1", "numero": "318", "questao": "As placas brancas de indicação são usadas para:", "alternativas": {"A": "Informar nomes de ruas ou bairros.", "B": "Proibir estacionamento.", "C": "Alertar sobre curvas.", "D": "Informar velocidades máximas."}, "resposta": "A", "comentario": "Placas de fundo branco identificam locais e vias."},
    {"modulo": "1", "numero": "319", "questao": "O que o motorista deve fazer ao ver uma placa verde indicando Saída 500 m?", "alternativas": {"A": "Reduzir gradualmente e preparar-se para sair da rodovia.", "B": "Parar no acostamento.", "C": "Acelerar para não perder a saída.", "D": "Ignorar se o destino for próximo."}, "resposta": "A", "comentario": "Essa placa antecipa a aproximação de uma saída."},
    {"modulo": "1", "numero": "320", "questao": "Uma placa azul com o símbolo de uma colher e garfo indica:", "alternativas": {"A": "Restaurante ou lanchonete próxima.", "B": "Proibição de parar.", "C": "Área de carga e descarga.", "D": "Serviço mecânico."}, "resposta": "A", "comentario": "Símbolo de alimentação disponível."},
    {"modulo": "1", "numero": "321", "questao": "Qual é a principal diferença entre uma placa de regulamentação e uma de indicação?", "alternativas": {"A": "A de regulamentação impõe regras; a de indicação apenas informa.", "B": "A de indicação tem formato redondo.", "C": "A de regulamentação é opcional.", "D": "A de indicação é sempre marrom."}, "resposta": "A", "comentario": "Placas de regulamentação são obrigatórias; as de indicação orientam."},
    {"modulo": "1", "numero": "322", "questao": "O que o motorista entende ao ver uma placa azul com o símbolo de uma cama?", "alternativas": {"A": "Indica um local com hospedagem disponível.", "B": "Indica área de descanso obrigatória.", "C": "Indica hospital.", "D": "Indica ponto de ônibus."}, "resposta": "A", "comentario": "Símbolo de hospedagem, útil em longas viagens."},
    {"modulo": "1", "numero": "323", "questao": "As placas de indicação também podem mostrar:", "alternativas": {"A": "A distância em quilômetros até cidades próximas.", "B": "O limite de velocidade.", "C": "O tipo de solo da pista.", "D": "O horário de funcionamento de pedágios."}, "resposta": "A", "comentario": "Informam distâncias e destinos."},
    {"modulo": "1", "numero": "324", "questao": "Em uma rodovia, a placa verde Retorno a 2 km informa:", "alternativas": {"A": "A distância até o local onde é permitido retornar.", "B": "Que é proibido retornar.", "C": "Que há um pedágio em 2 km.", "D": "Que o trânsito é mão única."}, "resposta": "A", "comentario": "Sinaliza o ponto autorizado para retorno."},
    {"modulo": "1", "numero": "325", "questao": "Por que é importante que o motorista saiba identificar placas de indicação rapidamente?", "alternativas": {"A": "Porque ajudam na tomada de decisões sem distrações perigosas.", "B": "Porque evitam multas.", "C": "Porque substituem os mapas digitais.", "D": "Porque reduzem o consumo de combustível."}, "resposta": "A", "comentario": "A leitura rápida evita decisões de última hora."},
    {"modulo": "1", "numero": "326", "questao": "Uma placa azul com símbolo de uma cruz vermelha representa:", "alternativas": {"A": "Serviço médico ou pronto-atendimento.", "B": "Local religioso.", "C": "Cemitério.", "D": "Proibição de parar."}, "resposta": "A", "comentario": "A cruz vermelha simboliza atendimento médico."},
    {"modulo": "1", "numero": "327", "questao": "O que significa uma placa verde indicando Desvio com seta direcional?", "alternativas": {"A": "Um caminho alternativo temporário.", "B": "Que é proibido seguir em frente.", "C": "Que há hospital.", "D": "Que é um acesso a estacionamento."}, "resposta": "A", "comentario": "Indica rotas alternativas durante bloqueios."},
    {"modulo": "1", "numero": "328", "questao": "Uma placa azul com o símbolo de uma bomba de combustível informa:", "alternativas": {"A": "A presença de posto de abastecimento adiante.", "B": "Que é proibido abastecer.", "C": "Que há mecânica de emergência.", "D": "Que a via termina."}, "resposta": "A", "comentario": "Informa posto de combustível próximo."},
    {"modulo": "1", "numero": "329", "questao": "Por que as placas de indicação de serviços têm fundo azul?", "alternativas": {"A": "Porque o azul é associado à informação e tranquilidade.", "B": "Porque é mais visível à noite.", "C": "Porque é a cor usada em obras.", "D": "Porque diferencia pedágios."}, "resposta": "A", "comentario": "O azul facilita leitura e transmite segurança."},
    {"modulo": "1", "numero": "330", "questao": "Como as placas de indicação contribuem para a segurança viária?", "alternativas": {"A": "Evita paradas indevidas e decisões de última hora, guiando o fluxo de forma previsível.", "B": "Reduzem o número de pedestres.", "C": "Substituem o trabalho de agentes.", "D": "Eliminam semáforos."}, "resposta": "A", "comentario": "Orientam o condutor e reduzem manobras bruscas."},
    {"modulo": "1", "numero": "370", "questao": "Quando duas vias se cruzam e ambas possuem placa PARE, o condutor deve:", "alternativas": {"A": "Parar e ceder a passagem a quem chegou primeiro ao cruzamento.", "B": "Avançar rapidamente.", "C": "Aguardar buzina do outro condutor.", "D": "Manter prioridade automática."}, "resposta": "A", "comentario": "Nessa situação, aplica-se a regra de cortesia e prudência: cede passagem quem chega depois."},
    {"modulo": "1", "numero": "371", "questao": "Como deve ser usada a faixa de aceleração?", "alternativas": {"A": "Acelerando gradualmente até atingir a velocidade da via principal.", "B": "Parando para observar o trânsito.", "C": "Entrando direto na pista principal.", "D": "Reduzindo totalmente a velocidade."}, "resposta": "A", "comentario": "Serve para ajustar a velocidade antes de se unir ao fluxo."},
]

async def add_questions():
    mongo_url = os.environ.get('MONGO_URL')
    db_name = os.environ.get('DB_NAME', 'detran_quiz')
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    questions_collection = db.questions
    
    existing = await questions_collection.find({"modulo": "1"}, {"numero": 1}).to_list(length=1000)
    existing_nums = {q.get("numero") for q in existing}
    
    questions_to_insert = []
    for q in NEW_QUESTIONS:
        if q["numero"] not in existing_nums:
            question_doc = {
                "_id": str(uuid.uuid4()),
                "modulo": q["modulo"],
                "numero": q["numero"],
                "questao": q["questao"],
                "alternativas": q["alternativas"],
                "resposta": q["resposta"],
                "comentario": q["comentario"],
                "has_image": False,
                "image_placeholder": None
            }
            questions_to_insert.append(question_doc)
    
    if questions_to_insert:
        await questions_collection.insert_many(questions_to_insert)
        print(f"Inseridas {len(questions_to_insert)} novas questões!")
    else:
        print("Nenhuma questão nova para inserir.")
    
    print("\n=== Resumo do Banco de Dados ===")
    for modulo in ["1", "2", "3", "4"]:
        count = await questions_collection.count_documents({"modulo": modulo})
        print(f"Módulo {modulo}: {count} questões")
    
    total = await questions_collection.count_documents({})
    print(f"\nTotal de questões: {total}")
    
    client.close()

if __name__ == "__main__":
    asyncio.run(add_questions())
