#!/usr/bin/env python3
"""
Script to add second batch of extracted questions to the database (questions 81-130)
"""

import asyncio
import uuid
from motor.motor_asyncio import AsyncIOMotorClient
import os
from dotenv import load_dotenv

load_dotenv()

# Extracted questions from Module 1 (questions 81-130)
NEW_QUESTIONS = [
    {"modulo": "1", "numero": "81", "questao": "Lucas conduz seu carro e vê a placa de proibido virar à direita junto a uma faixa contínua amarela. O que isso significa?", "alternativas": {"A": "É proibido virar à direita e também mudar de faixa naquele trecho.", "B": "Pode virar se não houver veículos.", "C": "É uma advertência temporária.", "D": "Serve apenas para ônibus."}, "resposta": "A", "comentario": "A combinação reforça a proibição de conversão e mudança de direção."},
    {"modulo": "1", "numero": "82", "questao": "Marcos dirige em uma rodovia de pista simples e vê a placa de mantenha-se à direita. O que deve fazer?", "alternativas": {"A": "Continuar trafegando pela direita da via.", "B": "Manter-se no centro da pista.", "C": "Ir para a faixa da esquerda.", "D": "Encostar no acostamento e parar."}, "resposta": "A", "comentario": "O sentido de circulação no Brasil é pela direita, a placa reforça essa regra."},
    {"modulo": "1", "numero": "83", "questao": "O formato e as cores da placa Proibido Virar à Esquerda indicam que se trata de:", "alternativas": {"A": "Uma placa de regulamentação.", "B": "Uma placa de advertência.", "C": "Uma placa educativa.", "D": "Uma placa de serviço."}, "resposta": "A", "comentario": "As placas circulares com fundo branco e borda vermelha expressam proibições, pertencendo à categoria de regulamentação."},
    {"modulo": "1", "numero": "84", "questao": "Por que o motorista deve redobrar a atenção ao se deparar com a placa de mão dupla?", "alternativas": {"A": "Passará a ter veículos vindo em sentido oposto.", "B": "Poderá usar toda a pista livremente.", "C": "Não haverá mais sinalização horizontal.", "D": "O tráfego será apenas de pedestres."}, "resposta": "A", "comentario": "A coexistência de sentidos opostos exige cuidado redobrado e respeito à faixa divisória."},
    {"modulo": "1", "numero": "85", "questao": "O que a placa de sentidos permitidos (frente e esquerda) indica?", "alternativas": {"A": "O condutor deve seguir em frente ou virar à esquerda.", "B": "O condutor deve obrigatoriamente virar à direita.", "C": "O condutor deve retornar.", "D": "O condutor deve parar."}, "resposta": "A", "comentario": "As duas setas indicam as únicas manobras permitidas — seguir ou virar à esquerda."},
    {"modulo": "1", "numero": "86", "questao": "O que a placa de interseção em T indica?", "alternativas": {"A": "Que a via termina à frente e o motorista deve virar à direita ou à esquerda.", "B": "Que há uma lombada.", "C": "Que a pista é de mão dupla.", "D": "Que há um túnel."}, "resposta": "A", "comentario": "A placa adverte sobre o fim da via e a necessidade de conversão."},
    {"modulo": "1", "numero": "87", "questao": "O que a placa de proibido virar à esquerda pretende evitar?", "alternativas": {"A": "Conflitos de tráfego e acidentes em cruzamentos.", "B": "Paradas prolongadas.", "C": "Redução de velocidade.", "D": "Conversões à direita."}, "resposta": "A", "comentario": "Essa sinalização organiza o fluxo e evita colisões laterais e frontais."},
    {"modulo": "1", "numero": "88", "questao": "O que acontece se um carro particular trafegar em via sinalizada com placa de faixa exclusiva de ônibus?", "alternativas": {"A": "O condutor comete infração de trânsito.", "B": "A via é livre para todos.", "C": "O veículo tem prioridade sobre o ônibus.", "D": "Nenhuma consequência legal."}, "resposta": "A", "comentario": "Trafegar em faixa exclusiva é infração de natureza média, conforme o CTB."},
    {"modulo": "1", "numero": "89", "questao": "O que a placa de cruzamento de vias está avisando?", "alternativas": {"A": "Que existe um cruzamento à frente, onde podem vir carros dos dois lados.", "B": "Que a via é sem saída.", "C": "Que há uma lombada à frente.", "D": "Que é obrigatório virar à direita."}, "resposta": "A", "comentario": "Essa placa alerta para o encontro de duas vias, exigindo cuidado e redução de velocidade."},
    {"modulo": "1", "numero": "90", "questao": "O que a placa de junções sucessivas está avisando?", "alternativas": {"A": "Que há duas entradas ou saídas próximas, uma à esquerda e outra à direita.", "B": "Que existe um semáforo à frente.", "C": "Que há uma lombada dupla.", "D": "Que é proibido virar à esquerda."}, "resposta": "A", "comentario": "A placa indica junções próximas em sentidos opostos, exigindo cuidado."},
    {"modulo": "1", "numero": "91", "questao": "O que a placa de parada obrigatória à frente está avisando?", "alternativas": {"A": "Que há uma parada obrigatória mais à frente.", "B": "Que o motorista deve seguir sem parar.", "C": "Que há um posto policial.", "D": "Que é o fim da pista."}, "resposta": "A", "comentario": "Essa placa prepara o condutor para parar completamente adiante."},
    {"modulo": "1", "numero": "92", "questao": "O que a placa de via lateral à esquerda está avisando?", "alternativas": {"A": "Que há uma via entrando pela esquerda.", "B": "Que a pista é de mão dupla.", "C": "Que existe uma lombada.", "D": "Que é proibido virar à esquerda."}, "resposta": "A", "comentario": "A placa indica que outra via se junta à estrada principal pela esquerda."},
    {"modulo": "1", "numero": "93", "questao": "O que a placa de depressão indica ao condutor?", "alternativas": {"A": "Que há uma depressão ou abaixamento na pista à frente.", "B": "Que existe uma lombada.", "C": "Que há pista irregular.", "D": "Que o pavimento é novo."}, "resposta": "A", "comentario": "A placa alerta para um rebaixamento que pode causar impacto na suspensão do veículo."},
    {"modulo": "1", "numero": "94", "questao": "O que a placa de rotatória indica ao condutor?", "alternativas": {"A": "Que há uma rotatória à frente.", "B": "Que a via é sem saída.", "C": "Que existe um retorno proibido.", "D": "Que há um quebra-molas à frente."}, "resposta": "A", "comentario": "A placa adverte que o condutor se aproxima de uma interseção circular (rotatória)."},
    {"modulo": "1", "numero": "95", "questao": "O que a placa de aclive acentuado indica ao condutor?", "alternativas": {"A": "Que há uma subida forte à frente.", "B": "Que a pista está em declive.", "C": "Que há uma lombada.", "D": "Que existe um pedágio logo adiante."}, "resposta": "A", "comentario": "A placa alerta sobre um trecho de aclive, ou seja, uma subida íngreme."},
    {"modulo": "1", "numero": "96", "questao": "O que a placa de bifurcação indica?", "alternativas": {"A": "Que a via se divide em duas direções à frente.", "B": "Que há um cruzamento com semáforo.", "C": "Que a pista é de mão dupla.", "D": "Que a via termina logo adiante."}, "resposta": "A", "comentario": "A placa alerta que a estrada se divide e o condutor deve decidir o sentido com antecedência."},
    {"modulo": "1", "numero": "97", "questao": "O que a placa de semáforo à frente indica?", "alternativas": {"A": "Que há um semáforo à frente.", "B": "Que a via é preferencial.", "C": "Que há uma lombada dupla.", "D": "Que é permitido ultrapassar."}, "resposta": "A", "comentario": "A placa alerta que o condutor se aproxima de um cruzamento com controle de semáforo."},
    {"modulo": "1", "numero": "98", "questao": "O que a placa de lombada indica?", "alternativas": {"A": "Que há uma lombada ou saliência na pista à frente.", "B": "Que há um buraco na via.", "C": "Que o trânsito está livre.", "D": "Que há pedágio."}, "resposta": "A", "comentario": "A placa alerta o motorista sobre a presença de uma elevação na pista."},
    {"modulo": "1", "numero": "99", "questao": "O que a placa de pista sinuosa à esquerda quer dizer para o motorista?", "alternativas": {"A": "Que a estrada tem várias curvas, começando para a esquerda.", "B": "Que há um cruzamento com semáforo.", "C": "Que deve virar à esquerda logo.", "D": "Que há um quebra-molas à frente."}, "resposta": "A", "comentario": "Essa placa avisa que vem um trecho com muitas curvas, exigindo mais cuidado."},
    {"modulo": "1", "numero": "100", "questao": "O que a placa de declive acentuado quer dizer?", "alternativas": {"A": "Que há uma descida forte à frente.", "B": "Que a pista está com lombadas.", "C": "Que há uma subida acentuada.", "D": "Que a pista é irregular."}, "resposta": "A", "comentario": "A placa alerta sobre um trecho em declive, que exige controle de velocidade."},
    {"modulo": "1", "numero": "101", "questao": "O que a placa de trânsito de máquinas agrícolas indica?", "alternativas": {"A": "Que há circulação de tratores ou máquinas agrícolas na via.", "B": "Que há posto de combustível à frente.", "C": "Que é uma estrada urbana.", "D": "Que é proibido o trânsito de veículos grandes."}, "resposta": "A", "comentario": "O símbolo do trator indica possível presença de veículos agrícolas lentos."},
    {"modulo": "1", "numero": "102", "questao": "O que a placa de trânsito de pedestres indica?", "alternativas": {"A": "Que há pedestres circulando ou atravessando a via.", "B": "Que há ciclistas à frente.", "C": "Que o trânsito é só de veículos pesados.", "D": "Que é uma estrada rural."}, "resposta": "A", "comentario": "A placa alerta o condutor sobre a presença frequente de pedestres na pista."},
    {"modulo": "1", "numero": "103", "questao": "O que indica a placa de ciclovia ou ciclofaixa?", "alternativas": {"A": "Circulação exclusiva de bicicletas.", "B": "Proibição de circulação de bicicletas.", "C": "Faixa compartilhada entre carros e bicicletas.", "D": "Proibição de pedestres."}, "resposta": "A", "comentario": "A placa R-34 garante o uso exclusivo da via ou faixa aos ciclistas."},
    {"modulo": "1", "numero": "104", "questao": "O que indica a placa de sentidos permitidos (frente e direita)?", "alternativas": {"A": "O condutor deve seguir em frente ou virar à direita.", "B": "O condutor deve virar à esquerda.", "C": "É proibido estacionar.", "D": "Deve realizar retorno."}, "resposta": "A", "comentario": "As duas setas indicam que apenas essas direções são permitidas."},
    {"modulo": "1", "numero": "105", "questao": "O que indica a placa de sentido obrigatório em frente?", "alternativas": {"A": "Obrigação de seguir em frente.", "B": "Obrigação de virar à direita.", "C": "Proibição de seguir em frente.", "D": "Permissão para retorno."}, "resposta": "A", "comentario": "A seta única para cima representa movimento obrigatório no sentido indicado."},
    {"modulo": "1", "numero": "106", "questao": "O que indica a placa de faixa exclusiva de caminhões?", "alternativas": {"A": "Que a circulação é exclusiva para caminhões.", "B": "Que caminhões estão proibidos de circular.", "C": "Que ônibus e caminhões compartilham a faixa.", "D": "Que apenas veículos leves podem trafegar."}, "resposta": "A", "comentario": "A placa autoriza e delimita o espaço exclusivo para caminhões."},
    {"modulo": "1", "numero": "107", "questao": "O que indica a placa de faixa exclusiva de ônibus?", "alternativas": {"A": "Que a via ou faixa é de circulação exclusiva de ônibus.", "B": "Que o estacionamento é permitido a ônibus.", "C": "Que é proibido o trânsito de ônibus.", "D": "Que é ponto de parada de ônibus."}, "resposta": "A", "comentario": "A placa R-32 indica exclusividade de circulação, não parada ou estacionamento."},
    {"modulo": "1", "numero": "108", "questao": "O que indica a placa de duplo sentido de circulação?", "alternativas": {"A": "Que a via passa a ter duplo sentido de circulação.", "B": "Que há mão única à direita.", "C": "Que o sentido é obrigatório para frente.", "D": "Que a via é exclusiva para ônibus."}, "resposta": "A", "comentario": "As duas setas em direções opostas representam tráfego nos dois sentidos."},
    {"modulo": "1", "numero": "109", "questao": "O que indica a placa de pista dividida?", "alternativas": {"A": "Que a via passará a ter duas pistas separadas por canteiro central.", "B": "Que a via terá apenas uma faixa estreita.", "C": "Que há obras no local.", "D": "Que o trânsito será interrompido."}, "resposta": "A", "comentario": "A placa adverte o motorista sobre o início de uma pista com separação física entre os sentidos."},
    {"modulo": "1", "numero": "110", "questao": "O que indica a placa de início de separação de fluxos?", "alternativas": {"A": "Que a via passará a ter separação física dividindo os fluxos de mesmo sentido de circulação.", "B": "Que há um desvio temporário.", "C": "Que a via termina adiante.", "D": "Que há um cruzamento sem sinalização."}, "resposta": "A", "comentario": "A placa alerta para o início de separação da pista, aumentando a segurança e a fluidez do tráfego."},
    {"modulo": "1", "numero": "111", "questao": "O que indica a placa de via sem saída?", "alternativas": {"A": "Que a via termina adiante e não possui saída para outra rua.", "B": "Que há um cruzamento logo à frente.", "C": "Que o trânsito é de mão dupla.", "D": "Que existe um pedágio adiante."}, "resposta": "A", "comentario": "A placa alerta o motorista de que a via termina, deve ser observada antes de entrar na rua."},
    {"modulo": "1", "numero": "112", "questao": "O que indica a placa de fim de pista dupla?", "alternativas": {"A": "Que a via voltará a ter mão dupla, sem separação física entre os sentidos.", "B": "Que há início de túnel.", "C": "Que o trânsito será interrompido.", "D": "Que haverá pedágio adiante."}, "resposta": "A", "comentario": "A placa alerta para o término da divisão entre fluxos opostos, a atenção deve ser redobrada."},
    {"modulo": "1", "numero": "113", "questao": "O que indica a placa de proibido trânsito de motocicletas?", "alternativas": {"A": "Que é proibida a circulação de motocicletas, motonetas e ciclomotores.", "B": "Que é obrigatória a circulação de motocicletas.", "C": "Que é permitida a circulação de bicicletas.", "D": "Que é exclusivo para caminhões."}, "resposta": "A", "comentario": "Essa placa restringe completamente a entrada e circulação de veículos motorizados de duas rodas."},
    {"modulo": "1", "numero": "114", "questao": "O que indica a placa de proibido trânsito de ônibus?", "alternativas": {"A": "Que é proibida a circulação de ônibus.", "B": "Que a via é exclusiva para ônibus.", "C": "Que é obrigatório o transporte coletivo.", "D": "Que é permitido o trânsito apenas de caminhões."}, "resposta": "A", "comentario": "A placa restringe o tráfego de ônibus no trecho sinalizado."},
    {"modulo": "1", "numero": "115", "questao": "O que indica a placa de passagem de nível com barreira?", "alternativas": {"A": "Que existe cruzamento com linha férrea à frente, protegido por cancelas.", "B": "Que há um pedágio na via.", "C": "Que a pista está bloqueada por obras.", "D": "Que o trânsito é exclusivo para trens."}, "resposta": "A", "comentario": "A placa alerta para cruzamento ferroviário onde há cancelas automáticas ou manuais."},
    {"modulo": "1", "numero": "116", "questao": "O que indica a placa de passagem de nível sem barreira?", "alternativas": {"A": "Que há um cruzamento entre a pista e uma linha de trem, sem cancelas de proteção.", "B": "Que a via está interditada para veículos.", "C": "Que há um posto policial à frente.", "D": "Que existe uma ponte com pedágio."}, "resposta": "A", "comentario": "O motorista deve reduzir a velocidade, parar e verificar se há trem se aproximando."},
    {"modulo": "1", "numero": "117", "questao": "O que indica a placa de curva à direita?", "alternativas": {"A": "Que há uma curva à direita à frente.", "B": "Que o retorno é obrigatório.", "C": "Que há uma interseção em T.", "D": "Que há uma curva acentuada à esquerda."}, "resposta": "A", "comentario": "A placa A-2b avisa o condutor sobre uma curva moderada à direita, exigindo atenção."},
    {"modulo": "1", "numero": "118", "questao": "O que indica a placa de curva acentuada à esquerda?", "alternativas": {"A": "Que há uma curva acentuada à esquerda à frente.", "B": "Que há uma conversão obrigatória à esquerda.", "C": "Que é permitido o retorno.", "D": "Que há uma interseção em T."}, "resposta": "A", "comentario": "A placa A-1a alerta sobre curva acentuada à esquerda e exige atenção redobrada."},
    {"modulo": "1", "numero": "119", "questao": "O que indica a placa de pedestre ande pela direita?", "alternativas": {"A": "Que o pedestre deve andar pela direita da via.", "B": "Que o pedestre pode atravessar livremente.", "C": "Que o pedestre deve permanecer parado.", "D": "Que o pedestre deve andar pela esquerda."}, "resposta": "A", "comentario": "A seta indica o lado da via destinado à circulação do pedestre."},
    {"modulo": "1", "numero": "120", "questao": "O que indica a placa de pedestre ande pela esquerda?", "alternativas": {"A": "Que o pedestre deve andar pela esquerda da via.", "B": "Que o pedestre deve atravessar a rua.", "C": "Que o pedestre deve permanecer parado.", "D": "Que é proibido andar a pé."}, "resposta": "A", "comentario": "O pictograma indica a posição correta de circulação do pedestre no bordo da pista."},
    {"modulo": "1", "numero": "121", "questao": "O que indica a placa de veículos pesados mantenham-se à direita?", "alternativas": {"A": "Que ônibus e caminhões devem manter-se na faixa da direita.", "B": "Que todos os veículos devem estacionar.", "C": "Que veículos leves devem trafegar na direita.", "D": "Que o trânsito é exclusivo para caminhões."}, "resposta": "A", "comentario": "Obriga veículos pesados a circularem na faixa da direita, garantindo fluidez e segurança."},
    {"modulo": "1", "numero": "122", "questao": "O que indica a placa de ciclovia e via de pedestres?", "alternativas": {"A": "Que os pedestres devem circular à esquerda e os ciclistas à direita.", "B": "Que a via é exclusiva para pedestres.", "C": "Que os ciclistas devem ocupar todo o espaço.", "D": "Que o trânsito é proibido para bicicletas."}, "resposta": "A", "comentario": "A linha vertical indica a separação obrigatória entre pedestres e ciclistas."},
    {"modulo": "1", "numero": "123", "questao": "O que o condutor deve fazer ao ver a placa de lombada?", "alternativas": {"A": "Reduzir a velocidade para passar com segurança sobre a lombada.", "B": "Acelerar para não sentir o impacto.", "C": "Frear bruscamente em cima da lombada.", "D": "Buzinar para avisar os pedestres."}, "resposta": "A", "comentario": "A passagem deve ser feita em baixa velocidade, de forma suave e contínua."},
    {"modulo": "1", "numero": "124", "questao": "O que o motorista deve evitar dentro da rotatória?", "alternativas": {"A": "Paradas bruscas e mudanças repentinas de faixa.", "B": "Uso da seta.", "C": "Observar os espelhos retrovisores.", "D": "Circular em baixa velocidade."}, "resposta": "A", "comentario": "Movimentos inesperados dentro da rotatória causam risco de colisão."},
    {"modulo": "1", "numero": "125", "questao": "O que o motorista deve fazer ao ver a placa de animais na pista?", "alternativas": {"A": "Reduzir a velocidade e ficar atento a possíveis animais na via.", "B": "Usar buzina para afastar os animais.", "C": "Continuar na mesma velocidade.", "D": "Desviar para o acostamento."}, "resposta": "A", "comentario": "Animais podem cruzar de repente, a velocidade reduzida aumenta o tempo de reação."},
    {"modulo": "1", "numero": "126", "questao": "O que significa a placa de proibido trânsito de pedestres?", "alternativas": {"A": "É proibida a circulação de pedestres.", "B": "É permitido o trânsito de pedestres.", "C": "É área de travessia de pedestres.", "D": "É passagem obrigatória para pedestres."}, "resposta": "A", "comentario": "A faixa vermelha sobre o símbolo do pedestre indica proibição de circulação."},
    {"modulo": "1", "numero": "127", "questao": "O que significa a placa de animais na pista?", "alternativas": {"A": "Que pode haver animais de grande porte atravessando a pista.", "B": "Que o local é exclusivo para pastagem.", "C": "Que a via é fechada para veículos.", "D": "Que o motorista pode acelerar."}, "resposta": "A", "comentario": "A placa alerta sobre a presença de bois, vacas ou outros animais na pista."},
    {"modulo": "1", "numero": "128", "questao": "Onde é mais comum encontrar a placa de máquinas agrícolas?", "alternativas": {"A": "Em estradas rurais e próximas a fazendas.", "B": "Em centros urbanos.", "C": "Em estacionamentos.", "D": "Em túneis e viadutos."}, "resposta": "A", "comentario": "É usada para alertar motoristas sobre o trânsito de máquinas agrícolas."},
    {"modulo": "1", "numero": "129", "questao": "Onde geralmente é instalada a placa de proibido trânsito de pedestres?", "alternativas": {"A": "Em pontes, viadutos, túneis e vias expressas.", "B": "Em estacionamentos subterrâneos.", "C": "Em faixas de pedestre.", "D": "Em zonas escolares."}, "resposta": "A", "comentario": "Esses locais não possuem área segura para circulação a pé."},
    {"modulo": "1", "numero": "130", "questao": "Paula dirige à noite e passa por um bairro residencial com a placa de proibido uso de buzina. Qual é a conduta correta?", "alternativas": {"A": "Evitar buzinar, inclusive para cumprimentos.", "B": "Usar buzina curta para se anunciar.", "C": "Tocar a buzina em intervalos.", "D": "Reduzir o som, mas buzinar se quiser."}, "resposta": "A", "comentario": "O ruído noturno é ainda mais perturbador e deve ser evitado."},
]

async def add_questions():
    mongo_url = os.environ.get('MONGO_URL')
    db_name = os.environ.get('DB_NAME', 'detran_quiz')
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    questions_collection = db.questions
    
    # Get existing question numbers to avoid duplicates
    existing = await questions_collection.find({"modulo": "1"}, {"numero": 1}).to_list(length=1000)
    existing_nums = {q.get("numero") for q in existing}
    
    questions_to_insert = []
    for q in NEW_QUESTIONS:
        if q["numero"] not in existing_nums:
            question_doc = {
                "_id": str(uuid.uuid4()),
                "modulo": q["modulo"],
                "numero": q["numero"],
                "questao": q["questao"],
                "alternativas": q["alternativas"],
                "resposta": q["resposta"],
                "comentario": q["comentario"],
                "has_image": False,
                "image_placeholder": None
            }
            questions_to_insert.append(question_doc)
    
    if questions_to_insert:
        await questions_collection.insert_many(questions_to_insert)
        print(f"Inseridas {len(questions_to_insert)} novas questões!")
    else:
        print("Nenhuma questão nova para inserir.")
    
    # Print summary
    print("\n=== Resumo do Banco de Dados ===")
    for modulo in ["1", "2", "3", "4"]:
        count = await questions_collection.count_documents({"modulo": modulo})
        print(f"Módulo {modulo}: {count} questões")
    
    total = await questions_collection.count_documents({})
    print(f"\nTotal de questões: {total}")
    
    client.close()

if __name__ == "__main__":
    asyncio.run(add_questions())
