#!/usr/bin/env python3
"""
Script to add large batch of extracted questions (171-300 from Module 1)
"""

import asyncio
import uuid
from motor.motor_asyncio import AsyncIOMotorClient
import os
from dotenv import load_dotenv

load_dotenv()

# Questions 171-300 from Module 1
NEW_QUESTIONS = [
    {"modulo": "1", "numero": "171", "questao": "Rogério conduz um caminhão com peso total de 12 toneladas e vê a placa de peso máximo 10t. O que deve fazer?", "alternativas": {"A": "Não prosseguir e procurar rota alternativa.", "B": "Seguir com cuidado.", "C": "Reduzir a velocidade e passar assim mesmo.", "D": "Encostar e descarregar parte da carga."}, "resposta": "A", "comentario": "A placa R-14 indica o limite máximo de peso bruto total permitido no trecho. Veículos acima desse limite não podem transitar."},
    {"modulo": "1", "numero": "172", "questao": "Rogério dirige em uma avenida movimentada e vê a placa de proibido retorno. Ele deseja voltar no sentido contrário. O que deve fazer?", "alternativas": {"A": "Seguir em frente até encontrar sinalização que permita o retorno.", "B": "Parar no canteiro central e aguardar oportunidade.", "C": "Retornar com cuidado, se não houver trânsito.", "D": "Dar ré até o cruzamento anterior."}, "resposta": "A", "comentario": "Mesmo que pareça seguro, o retorno é proibido. O motorista deve buscar o próximo ponto permitido."},
    {"modulo": "1", "numero": "173", "questao": "Rogério dirige em uma rodovia e vê a placa de proibido ultrapassar. O que deve fazer?", "alternativas": {"A": "Manter-se atrás do veículo à frente até o fim do trecho sinalizado.", "B": "Ultrapassar devagar, se houver espaço.", "C": "Acelerar para ultrapassar rapidamente.", "D": "Usar o acostamento para ganhar tempo."}, "resposta": "A", "comentario": "A placa proíbe toda ultrapassagem até o ponto em que a sinalização indicar o fim da restrição."},
    {"modulo": "1", "numero": "174", "questao": "Rogério passa por um hospital e vê a placa de proibido uso de buzina. O que ele deve fazer?", "alternativas": {"A": "Evitar qualquer uso de buzina, para não causar ruído desnecessário.", "B": "Buzinar brevemente para alertar pedestres.", "C": "Aumentar o volume do som.", "D": "Acelerar para sair rápido da área."}, "resposta": "A", "comentario": "O uso de buzina é proibido em áreas sensíveis, como hospitais e escolas."},
    {"modulo": "1", "numero": "175", "questao": "A forma octogonal da placa PARE tem como objetivo:", "alternativas": {"A": "Ser reconhecida facilmente.", "B": "Indicar um tipo de serviço.", "C": "Mostrar que é uma placa temporária.", "D": "Reduzir o custo de fabricação."}, "resposta": "A", "comentario": "O formato octogonal é exclusivo da R-1 para garantir alta identificação visual em qualquer ângulo."},
    {"modulo": "1", "numero": "176", "questao": "Ao entrar em uma curva indicada pela placa de curva acentuada, com excesso de velocidade, o veículo tende a:", "alternativas": {"A": "Seguir reto.", "B": "Fazer a curva com mais facilidade.", "C": "Reduzir automaticamente a tração.", "D": "Girar sobre o próprio eixo."}, "resposta": "A", "comentario": "A força centrífuga empurra o veículo para fora da curva, especialmente à direita."},
    {"modulo": "1", "numero": "177", "questao": "Beatriz estaciona rapidamente com o pisca-alerta ligado em local com a placa de proibido estacionar. Essa ação é permitida?", "alternativas": {"A": "Não, pois o pisca-alerta não autoriza desrespeitar a proibição.", "B": "Sim, se o tempo for inferior a 5 minutos.", "C": "Sim, desde que permaneça dentro do carro.", "D": "Sim, se não houver fiscalização."}, "resposta": "A", "comentario": "A sinalização deve ser obedecida independentemente do tempo ou da presença de agentes."},
    {"modulo": "1", "numero": "178", "questao": "Bruno deseja deixar um passageiro em local com a placa de proibido parar. O que ele deve fazer?", "alternativas": {"A": "Seguir até um ponto onde a parada seja permitida.", "B": "Parar rapidamente e liberar o passageiro.", "C": "Estacionar com o pisca-alerta ligado.", "D": "Reduzir e parar sobre a calçada."}, "resposta": "A", "comentario": "Essa placa não permite qualquer parada, devendo o condutor procurar local autorizado."},
    {"modulo": "1", "numero": "179", "questao": "Carlos dirige à noite e vê a placa de proibido ultrapassar antes de uma curva acentuada. Por que essa proibição existe?", "alternativas": {"A": "Porque a visibilidade é reduzida e não há campo de visão suficiente para a manobra.", "B": "Porque há radar fixo mais adiante.", "C": "Porque é área urbana.", "D": "Porque a pista é larga."}, "resposta": "A", "comentario": "A placa evita manobras perigosas em locais onde a visibilidade é comprometida."},
    {"modulo": "1", "numero": "180", "questao": "Carlos dirige um automóvel e encontra a placa de proibido trânsito de veículos com inscrição Exceto veículos de emergência. O que significa?", "alternativas": {"A": "Somente ambulâncias, viaturas policiais e bombeiros podem circular naquele local.", "B": "Todos os carros podem entrar.", "C": "Caminhões também estão liberados.", "D": "É apenas sinalização educativa."}, "resposta": "A", "comentario": "As exceções descritas em placas complementares indicam permissão restrita a veículos em serviço público essencial."},
    {"modulo": "1", "numero": "181", "questao": "César vê a placa de proibido retorno junto de outra com o texto Exceto veículos de emergência. O que isso significa?", "alternativas": {"A": "Somente ambulâncias, bombeiros e viaturas em serviço podem fazer o retorno.", "B": "Todos os veículos podem retornar.", "C": "A placa está desativada.", "D": "A proibição é temporária."}, "resposta": "A", "comentario": "A placa complementar cria exceção específica autorizada pelo órgão de trânsito."},
    {"modulo": "1", "numero": "182", "questao": "Como a placa de veículos pesados à direita contribui para a segurança viária?", "alternativas": {"A": "Mantendo previsibilidade e separação de fluxos entre veículos leves e pesados.", "B": "Diminuindo a fiscalização eletrônica.", "C": "Reduzindo a necessidade de sinalização vertical.", "D": "Incentivando ultrapassagens em curva."}, "resposta": "A", "comentario": "Ordena o tráfego e reduz zonas de conflito em pistas de múltiplas faixas."},
    {"modulo": "1", "numero": "183", "questao": "Eduardo estaciona seu carro sobre uma calçada com a placa de proibido estacionar próxima. O que diz a lei?", "alternativas": {"A": "É infração grave estacionar sobre passeio, mesmo sem placa específica.", "B": "É permitido se não atrapalhar pedestres.", "C": "Só é proibido se houver sinalização vertical.", "D": "É infração leve."}, "resposta": "A", "comentario": "O CTB proíbe estacionar sobre calçadas, e a placa reforça a regra geral de segurança e acessibilidade."},
    {"modulo": "1", "numero": "184", "questao": "Em pista molhada, qual é a conduta segura ao encontrar a placa de curva?", "alternativas": {"A": "Reduzir mais a velocidade e evitar movimentos bruscos no volante.", "B": "Manter a velocidade e frear com força no meio da curva.", "C": "Ligar o pisca-alerta e parar.", "D": "Utilizar apenas o freio de mão."}, "resposta": "A", "comentario": "A aderência diminui e a curva torna-se mais perigosa em piso molhado."},
    {"modulo": "1", "numero": "185", "questao": "Em qual local urbano é mais comum a presença da placa de faixa exclusiva de ônibus?", "alternativas": {"A": "Em corredores exclusivos, avenidas com faixas de ônibus e terminais urbanos.", "B": "Em áreas escolares.", "C": "Em zonas rurais.", "D": "Em rodovias federais."}, "resposta": "A", "comentario": "É usada para garantir eficiência ao transporte coletivo urbano."},
    {"modulo": "1", "numero": "186", "questao": "Em qual situação a velocidade deve ser reduzida mesmo abaixo da indicada na placa?", "alternativas": {"A": "Sob chuva, neblina, buracos ou presença de pedestres.", "B": "Quando o veículo está novo.", "C": "Apenas à noite.", "D": "Quando não há radares."}, "resposta": "A", "comentario": "A velocidade deve sempre ser compatível com as condições da via e da visibilidade."},
    {"modulo": "1", "numero": "187", "questao": "Em qual situação é mais comum encontrar a placa de parada obrigatória à frente?", "alternativas": {"A": "Antes de cruzamentos com pouca visibilidade.", "B": "No início de pontes largas.", "C": "Em trechos de ultrapassagem.", "D": "Perto de postos de combustível."}, "resposta": "A", "comentario": "A advertência aumenta a segurança em locais de risco de colisão."},
    {"modulo": "1", "numero": "188", "questao": "Em uma rua sinalizada com Sentido Proibido, o motorista deve:", "alternativas": {"A": "Respeitar a proibição e buscar o sentido permitido.", "B": "Seguir em frente apenas para estacionar.", "C": "Usar o acostamento para continuar.", "D": "Fazer conversão proibida."}, "resposta": "A", "comentario": "O respeito à placa mantém o fluxo seguro e evita colisões frontais com quem vem no sentido correto."},
    {"modulo": "1", "numero": "189", "questao": "Juliana vê a placa de proibido virar à esquerda acompanhada de outra placa logo abaixo com a inscrição Exceto ônibus. O que isso significa?", "alternativas": {"A": "Apenas os ônibus podem realizar a conversão.", "B": "Todos os veículos estão liberados.", "C": "A proibição é temporária.", "D": "Que apenas ônibus estão proibidos de fazer a conversão."}, "resposta": "A", "comentario": "A placa complementar delimita a exceção para transporte coletivo, válida conforme regulamentação local."},
    {"modulo": "1", "numero": "190", "questao": "Juliana vê a placa de proibido ultrapassar acompanhada de uma faixa contínua dupla no pavimento. O que essa combinação indica?", "alternativas": {"A": "Que a proibição de ultrapassar é reforçada tanto pela sinalização vertical quanto pela horizontal.", "B": "Que pode ultrapassar se houver espaço.", "C": "Que vale apenas para caminhões.", "D": "Que a faixa é apenas decorativa."}, "resposta": "A", "comentario": "A sinalização horizontal complementa a vertical, reforçando a proibição total de ultrapassagem."},
    {"modulo": "1", "numero": "191", "questao": "Marcos conduz um caminhão e encontra a placa de proibido trânsito de caminhões acompanhada da inscrição Das 7h às 20h. O que isso significa?", "alternativas": {"A": "A proibição vale apenas dentro do horário indicado.", "B": "É proibido trafegar 24 horas.", "C": "A placa é apenas educativa.", "D": "Que ele pode trafegar livremente."}, "resposta": "A", "comentario": "As placas auxiliares definem horários específicos de restrição de circulação."},
    {"modulo": "1", "numero": "192", "questao": "Marina dirige em um aclive e encontra a placa de proibido ultrapassar. Qual é o principal risco de desobedecê-la?", "alternativas": {"A": "Colidir frontalmente com veículo vindo no sentido contrário.", "B": "Ser multada apenas.", "C": "Gastar mais combustível.", "D": "Perder o controle da direção."}, "resposta": "A", "comentario": "Nos aclives, o campo de visão é reduzido e a ultrapassagem pode causar colisões frontais."},
    {"modulo": "1", "numero": "193", "questao": "Marina está em local com a placa de proibido estacionar acompanhada de uma placa auxiliar Das 7h às 19h. Às 21h, ela estaciona. Está correta?", "alternativas": {"A": "Sim, pois a restrição vale apenas no horário indicado.", "B": "Não, a proibição é para 24 horas.", "C": "Apenas se for moradora da rua.", "D": "Somente se deixar o pisca-alerta ligado."}, "resposta": "A", "comentario": "Placas complementares definem restrições por faixa horária, fora do horário, o estacionamento é permitido."},
    {"modulo": "1", "numero": "194", "questao": "O condutor que deseja fazer o retorno em local sinalizado com Proibido virar à esquerda deve:", "alternativas": {"A": "Seguir até um ponto onde o retorno seja permitido.", "B": "Fazer o retorno imediatamente, com cuidado.", "C": "Parar e pedir orientação a pedestres.", "D": "Realizar a manobra de marcha a ré."}, "resposta": "A", "comentario": "A proibição de virar à esquerda inclui o ato de retornar. O motorista deve prosseguir até o próximo ponto liberado."},
    {"modulo": "1", "numero": "195", "questao": "O fundo vermelho e as letras brancas da placa PARE significam:", "alternativas": {"A": "Proibição e ordem obrigatória de parada total.", "B": "Alerta de obras na via.", "C": "Indicação de preferência.", "D": "Orientação de trajeto alternativo."}, "resposta": "A", "comentario": "A cor vermelha nas placas de regulamentação indica proibição ou obrigação, reforçando a ordem de parada."},
    {"modulo": "1", "numero": "196", "questao": "O que a placa de sentido obrigatório à direita e a placa de sentido de circulação pela esquerda têm em comum?", "alternativas": {"A": "Ambas determinam o movimento obrigatório dos veículos.", "B": "Ambas indicam perigo de curva.", "C": "Ambas liberam estacionamento.", "D": "Ambas têm formato retangular."}, "resposta": "A", "comentario": "Ambas são de regulamentação e orientam o sentido de fluxo."},
    {"modulo": "1", "numero": "197", "questao": "O que acontece se o condutor circular na rotatória no sentido contrário ao indicado pela placa?", "alternativas": {"A": "Comete infração grave e põe em risco os demais usuários.", "B": "Apenas recebe advertência verbal.", "C": "É permitido em horários de pouco movimento.", "D": "Nenhuma consequência."}, "resposta": "A", "comentario": "Circular no sentido contrário da via é infração grave, conforme art. 186, inciso I, do CTB."},
    {"modulo": "1", "numero": "198", "questao": "O que o pedestre deve fazer ao ver a placa de pedestres à esquerda?", "alternativas": {"A": "Caminhar pelo lado esquerdo da via compartilhada.", "B": "Andar livremente pela faixa de ciclista.", "C": "Atravessar no meio da pista.", "D": "Caminhar em qualquer sentido."}, "resposta": "A", "comentario": "A divisão da circulação facilita a previsibilidade de movimentos."},
    {"modulo": "1", "numero": "199", "questao": "O que representa o comportamento seguro ao ver a placa de trânsito de pedestres?", "alternativas": {"A": "Atenção redobrada, velocidade reduzida e empatia com quem atravessa.", "B": "Pressa e buzina.", "C": "Disputa de espaço com o pedestre.", "D": "Uso do farol alto."}, "resposta": "A", "comentario": "A direção defensiva valoriza a vida e evita atropelamentos."},
    {"modulo": "1", "numero": "200", "questao": "Onde existe a placa de interseção em T, se o condutor quiser seguir em frente, o que deve lembrar?", "alternativas": {"A": "Que a via termina e ele deve obrigatoriamente virar.", "B": "Que pode continuar reto se for de madrugada.", "C": "Que o cruzamento é preferencial para ele.", "D": "Que o trecho é de ultrapassagem livre."}, "resposta": "A", "comentario": "A interseção em T indica o fim da pista — seguir reto é perigoso e proibido."},
    {"modulo": "1", "numero": "201", "questao": "Por que a placa de mão dupla é essencial para a segurança viária?", "alternativas": {"A": "Porque alerta o condutor sobre o risco de veículos em sentido contrário.", "B": "Porque indica área de pedágio.", "C": "Porque proíbe paradas de ônibus.", "D": "Porque mostra o limite de peso da via."}, "resposta": "A", "comentario": "Essa informação evita colisões frontais e ultrapassagens perigosas."},
    {"modulo": "1", "numero": "202", "questao": "Por que a placa de passagem obrigatória é fundamental em rodovias de pista simples com ilhas de refúgio?", "alternativas": {"A": "Porque impede que veículos invadam a faixa contrária durante o contorno.", "B": "Porque indica estacionamento.", "C": "Porque aumenta o limite de velocidade.", "D": "Porque substitui o guard rail."}, "resposta": "A", "comentario": "A obediência à direção de passagem previne colisões frontais."},
    {"modulo": "1", "numero": "203", "questao": "Por que as placas de velocidade máxima podem ter diferentes valores em um mesmo trajeto?", "alternativas": {"A": "Porque o limite é ajustado conforme o tipo de via, tráfego e entorno.", "B": "Porque são colocadas aleatoriamente.", "C": "Porque indicam o limite mínimo.", "D": "Porque servem apenas de orientação."}, "resposta": "A", "comentario": "As condições locais determinam o limite adequado de velocidade."},
    {"modulo": "1", "numero": "204", "questao": "Por que as ultrapassagens são mais perigosas em vias com a placa de mão dupla?", "alternativas": {"A": "Porque há risco de colisão com veículos que vêm no sentido oposto.", "B": "Porque há menos curvas.", "C": "Porque o trânsito é mais lento.", "D": "Porque há pedestres em excesso."}, "resposta": "A", "comentario": "Em mão dupla, o cálculo errado de tempo e distância causa sinistros fatais."},
    {"modulo": "1", "numero": "205", "questao": "Por que é importante manter atenção redobrada no tipo de cruzamento indicado pela placa de cruzamento?", "alternativas": {"A": "Porque veículos podem vir em alta velocidade pela via transversal.", "B": "Porque a placa é difícil de ver.", "C": "Porque o asfalto é sempre molhado.", "D": "Porque o cruzamento é automático."}, "resposta": "A", "comentario": "Muitos sinistros ocorrem por falta de observação lateral."},
    {"modulo": "1", "numero": "206", "questao": "Por que é importante o uso da placa de ciclovia e via de pedestres?", "alternativas": {"A": "Para orientar a convivência segura entre pedestres e ciclistas.", "B": "Para restringir o uso de bicicletas.", "C": "Para proibir o trânsito de pedestres.", "D": "Para aumentar a velocidade dos ciclistas."}, "resposta": "A", "comentario": "Ela visa reduzir conflitos e promover segurança no trânsito não motorizado."},
    {"modulo": "1", "numero": "207", "questao": "Por que é importante respeitar a placa de altura máxima em túneis e passagens subterrâneas?", "alternativas": {"A": "Porque o desrespeito pode causar colisão da carga contra o teto, colocando em risco todos os usuários.", "B": "Porque o ar é mais úmido nesses locais.", "C": "Porque há pedágio próximo.", "D": "Porque é área de fiscalização."}, "resposta": "A", "comentario": "O excesso de altura pode causar sinistros e danos estruturais, exigindo interdição da via."},
    {"modulo": "1", "numero": "208", "questao": "Por que é importante respeitar o sentido de circulação indicado pela placa em áreas urbanas?", "alternativas": {"A": "Porque evita conflitos entre fluxos opostos e atropelamentos.", "B": "Porque ajuda a encontrar vagas de estacionamento.", "C": "Porque melhora o som do motor.", "D": "Porque reduz o gasto de combustível."}, "resposta": "A", "comentario": "O respeito ao sentido correto garante a previsibilidade do comportamento dos condutores."},
    {"modulo": "1", "numero": "209", "questao": "Por que a placa de semáforo à frente é importante em locais com curvas ou subidas?", "alternativas": {"A": "Porque o motorista pode não ver o semáforo a tempo.", "B": "Porque indica radar.", "C": "Porque mostra o limite de velocidade.", "D": "Porque indica o fim da pista."}, "resposta": "A", "comentario": "A sinalização antecipada evita freadas bruscas em locais de pouca visibilidade."},
    {"modulo": "1", "numero": "210", "questao": "Por que não se deve ultrapassar em trechos com a placa de via sem saída?", "alternativas": {"A": "Porque a via termina à frente.", "B": "Que há obras no local.", "C": "Que o trânsito será interrompido.", "D": "Que a via terá apenas uma faixa estreita."}, "resposta": "A", "comentario": "A via termina à frente e não possui saída para outra rua."},
    {"modulo": "1", "numero": "257", "questao": "Qual a recomendação sobre manter distância do veículo à frente?", "alternativas": {"A": "Manter distância adequada para poder reagir a imprevistos.", "B": "Colar no carro da frente para fechar trânsito.", "C": "Ultrapassar pela direita sempre.", "D": "Usar o celular para se distrair."}, "resposta": "A", "comentario": "Distância é pilar da direção defensiva, permitindo tempo de reação."},
    {"modulo": "1", "numero": "258", "questao": "O que se entende por conversão à esquerda?", "alternativas": {"A": "Manobra que cruza o fluxo oposto e exige atenção extra.", "B": "Uma ultrapassagem pela direita.", "C": "Estacionar na esquerda da via.", "D": "Ignorar sinais de prioridade."}, "resposta": "A", "comentario": "Conversão à esquerda envolve atravessar o fluxo contrário e requer paciência."},
    {"modulo": "1", "numero": "259", "questao": "Quando a faixa é destinada a ciclistas (ciclofaixa), o que é recomendado aos motoristas?", "alternativas": {"A": "Respeitar a faixa e dar espaço ao ciclista.", "B": "Ultrapassar rapidamente os ciclistas.", "C": "Parar sobre a ciclofaixa para desembarque.", "D": "Usar a ciclofaixa para estacionamento."}, "resposta": "A", "comentario": "Ciclofaixas delimitam espaço específico; motoristas devem respeitar e manter distância."},
    {"modulo": "1", "numero": "260", "questao": "Em caso de mensagens conflitantes (agente, semáforo, placa), qual é a sequência de prioridade?", "alternativas": {"A": "Agente de trânsito > semáforo > placas e marcas no solo.", "B": "Placa > semáforo > agente.", "C": "Semáforo > placa > agente.", "D": "Marca no solo > placa > semáforo."}, "resposta": "A", "comentario": "A hierarquia definida pelo CTB prioriza o agente em situações de conflito."},
    {"modulo": "1", "numero": "261", "questao": "Por que as infrações podem variar de leves a gravíssimas?", "alternativas": {"A": "Porque o risco e a gravidade do comportamento variam e as penas acompanham isso.", "B": "Porque os fiscais decidem aleatoriamente.", "C": "Porque depende do tipo de veículo.", "D": "Porque muda a cada cidade sem regra."}, "resposta": "A", "comentario": "O material explica que diferenças de risco resultam em penalidades distintas."},
    {"modulo": "1", "numero": "262", "questao": "Qual a recomendação sobre velocidade inteligente?", "alternativas": {"A": "Adaptar a velocidade conforme via, clima e tráfego, não só o limite.", "B": "Sempre dirigir no limite máximo permitido.", "C": "Andar sempre mais devagar que os demais.", "D": "Sempre usar piloto automático."}, "resposta": "A", "comentario": "Velocidade inteligente prioriza controle e segurança sobre a velocidade legal máxima."},
    {"modulo": "1", "numero": "263", "questao": "Em vias urbanas próximas a escolas, qual comportamento é esperado do condutor?", "alternativas": {"A": "Reduzir a velocidade e aumentar atenção por crianças e pedestres.", "B": "Aumentar velocidade para liberar a via.", "C": "Ultrapassar outros veículos.", "D": "Estacionar sobre a calçada."}, "resposta": "A", "comentario": "Áreas escolares demandam redução de velocidade e cuidado redobrado."},
    {"modulo": "1", "numero": "264", "questao": "O que define uma rodovia pavimentada?", "alternativas": {"A": "Via rural asfaltada ou de concreto que permite velocidades maiores com sinalização completa.", "B": "Uma via sem sinalização.", "C": "Uma via apenas para pedestres.", "D": "Uma rua urbana com muitos cruzamentos."}, "resposta": "A", "comentario": "Rodovias pavimentadas têm características de segurança e permitem velocidades maiores."},
    {"modulo": "1", "numero": "265", "questao": "Por que a educação no trânsito (placas brancas) aparece em trechos perigosos?", "alternativas": {"A": "Porque reforçam comportamentos que reduzem risco nesses pontos.", "B": "Porque não há lugar melhor para colocar placas.", "C": "Porque substituem radares.", "D": "Porque apenas aumentam a visibilidade do local."}, "resposta": "A", "comentario": "Placas educativas são colocadas onde reforçar a atenção tem efeito direto na segurança."},
    {"modulo": "1", "numero": "266", "questao": "Qual a função prática de uma faixa de aceleração em uma entrada de rodovia?", "alternativas": {"A": "Permitir que o veículo aumente velocidade e combine com o tráfego antes de inserir-se.", "B": "Forçar o motorista a frear.", "C": "Servir como estacionamento temporário.", "D": "Reduzir o número de faixas na rodovia."}, "resposta": "A", "comentario": "Faixa de aceleração ajuda a integrar com segurança o fluxo de veículos."},
    {"modulo": "1", "numero": "267", "questao": "Por que é errado entrar devagar na pista principal vindo da faixa de aceleração?", "alternativas": {"A": "Porque causa risco de colisão por diferença de velocidade com o tráfego.", "B": "Porque é legal em todos os casos.", "C": "Porque acelera o tráfego atrás.", "D": "Porque facilita a conversão."}, "resposta": "A", "comentario": "Entrar devagar cria descontinuidade no fluxo e pode provocar colisões traseiras."},
    {"modulo": "1", "numero": "268", "questao": "Como o condutor deve agir quanto às manobras de conversão?", "alternativas": {"A": "Usar calma, sinalizar e garantir visibilidade antes de executar a manobra.", "B": "Fazer rápidas manobras para poupar tempo.", "C": "Nunca sinalizar para confundir outros.", "D": "Ultrapassar pela direita ao converter."}, "resposta": "A", "comentario": "Conversões seguras exigem calma, sinalização e atenção à visibilidade."},
    {"modulo": "1", "numero": "269", "questao": "O que se espera do condutor ao se aproximar de um cruzamento sem sinalização?", "alternativas": {"A": "Conhecer e aplicar as regras de preferência para evitar impasses.", "B": "Aguardar sempre que outro veículo se mova.", "C": "Passar sem reduzir a velocidade.", "D": "Sempre ceder a quem gritar mais alto."}, "resposta": "A", "comentario": "Regras de preferência evitam conflitos e mantêm fluidez no cruzamento."},
    {"modulo": "1", "numero": "270", "questao": "Qual a diferença entre rodovia e estrada de terra no comportamento do condutor?", "alternativas": {"A": "Estradas de terra exigem redução de velocidade e mais cuidado devido à menor aderência.", "B": "Estradas de terra permitem velocidades maiores.", "C": "A lei não se aplica nelas.", "D": "São sempre seguras."}, "resposta": "A", "comentario": "Estradas de terra têm menos segurança e requerem condução mais lenta e cautelosa."},
]

async def add_questions():
    mongo_url = os.environ.get('MONGO_URL')
    db_name = os.environ.get('DB_NAME', 'detran_quiz')
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    questions_collection = db.questions
    
    existing = await questions_collection.find({"modulo": "1"}, {"numero": 1}).to_list(length=1000)
    existing_nums = {q.get("numero") for q in existing}
    
    questions_to_insert = []
    for q in NEW_QUESTIONS:
        if q["numero"] not in existing_nums:
            question_doc = {
                "_id": str(uuid.uuid4()),
                "modulo": q["modulo"],
                "numero": q["numero"],
                "questao": q["questao"],
                "alternativas": q["alternativas"],
                "resposta": q["resposta"],
                "comentario": q["comentario"],
                "has_image": False,
                "image_placeholder": None
            }
            questions_to_insert.append(question_doc)
    
    if questions_to_insert:
        await questions_collection.insert_many(questions_to_insert)
        print(f"Inseridas {len(questions_to_insert)} novas questões!")
    else:
        print("Nenhuma questão nova para inserir.")
    
    print("\n=== Resumo do Banco de Dados ===")
    for modulo in ["1", "2", "3", "4"]:
        count = await questions_collection.count_documents({"modulo": modulo})
        print(f"Módulo {modulo}: {count} questões")
    
    total = await questions_collection.count_documents({})
    print(f"\nTotal de questões: {total}")
    
    client.close()

if __name__ == "__main__":
    asyncio.run(add_questions())
