#!/usr/bin/env python3
"""
Script to populate the database with all 1153 questions from the PDF
This script will:
1. Clear existing questions
2. Insert all questions from the extracted data
"""

import asyncio
import uuid
from motor.motor_asyncio import AsyncIOMotorClient
import os
from dotenv import load_dotenv

load_dotenv()

# Module 1 - Placas, Cores e Caminhos (371 questions)
# Extracted from the PDF - first batch
MODULO_1_QUESTIONS = [
    {"modulo": "1", "numero": "1", "questao": "Ao ver a placa de \"Área Escolar\", o que o motorista deve fazer?", "alternativas": {"A": "Seguir na mesma velocidade, já que é uma rua comum.", "B": "Buzinar para avisar os pedestres.", "C": "Acelerar para passar antes do sinal vermelho.", "D": "Reduzir a velocidade e redobrar a atenção com crianças e pedestres."}, "resposta": "D", "comentario": "A placa alerta o condutor sobre o risco aumentado e exige prudência."},
    {"modulo": "1", "numero": "2", "questao": "Ao virar à direita ou à esquerda, qual atitude básica?", "alternativas": {"A": "Virar em alta velocidade.", "B": "Parar sobre a faixa de pedestres.", "C": "Sinalizar a manobra antes de virar.", "D": "Buzinar e entrar sem olhar."}, "resposta": "C", "comentario": "O condutor deve sempre sinalizar a direção antes de virar para avisar os demais usuários da via e evitar acidentes."},
    {"modulo": "1", "numero": "3", "questao": "Cruzamento sem semáforo. Você vai virar à esquerda e há pedestres iniciando a travessia na faixa. Ao mesmo tempo, vem carro no sentido contrário. O que fazer?", "alternativas": {"A": "Virar rápido no espaço entre eles.", "B": "Buzinar para todos saírem.", "C": "Parar, ceder passagem aos pedestres e também aos veículos do sentido contrário, só convertendo quando tudo estiver seguro e sinalizado.", "D": "Forçar a entrada com farol alto."}, "resposta": "C", "comentario": "Conforme estabelece o Art. 70 e o Art. 214, inciso IV do CTB, o pedestre que já iniciou a travessia na faixa tem prioridade absoluta."},
    {"modulo": "1", "numero": "4", "questao": "Cruzamento sem sinalização entre uma rodovia e uma via local. Quem tem preferência?", "alternativas": {"A": "Quem vem mais rápido pela via local.", "B": "Quem buzina.", "C": "Quem trafega pela rodovia.", "D": "Quem chega primeiro."}, "resposta": "C", "comentario": "Conforme estabelece o art. 29, inciso III, alínea 'a' do CTB."},
    {"modulo": "1", "numero": "5", "questao": "Em um cruzamento, se o agente de trânsito ordenar ao condutor que avance, mas o semáforo estiver vermelho, qual ordem deve ser obedecida?", "alternativas": {"A": "Ficar parado por causa do vermelho.", "B": "Buzinar e exigir o verde.", "C": "Seguir a ordem do agente, avançando com cuidado.", "D": "Fazer retorno para evitar a ordem."}, "resposta": "C", "comentario": "A sinalização de trânsito segue uma ordem de precedência hierárquica, sendo que as ordens do agente de trânsito prevalecem."},
    {"modulo": "1", "numero": "6", "questao": "Em um cruzamento de área escolar sem semáforo, onde há pedestres esperando para atravessar, qual é a conduta obrigatória do motorista?", "alternativas": {"A": "Acelerar e passar antes.", "B": "Parar sobre a faixa para mostrar presença.", "C": "Buzinar para liberar a passagem.", "D": "Parar e dar preferência de passagem aos pedestres."}, "resposta": "D", "comentario": "Conforme estabelece o art. 214, inciso IV do CTB."},
    {"modulo": "1", "numero": "7", "questao": "Em um cruzamento não sinalizado, qual é a ordem de preferência de passagem entre os veículos?", "alternativas": {"A": "Quem buzina mais.", "B": "Quem chegar primeiro e acelerar.", "C": "Quem vem pela direita.", "D": "O maior veículo."}, "resposta": "C", "comentario": "Conforme estabelece o Art. 29, inciso III do CTB."},
    {"modulo": "1", "numero": "8", "questao": "Em cruzamento sem sinalização, quem tem preferência?", "alternativas": {"A": "O maior veículo sempre.", "B": "Quem buzina mais.", "C": "Quem vem pela esquerda.", "D": "O veículo que vem pela sua direita."}, "resposta": "D", "comentario": "Regra da direita - Art. 29, inciso III do CTB."},
    {"modulo": "1", "numero": "9", "questao": "Um condutor que está em uma estrada de terra, em via rural, não vê placa de sinalização e conduz o veículo com velocidade superior 60 km/h. A ação está correta?", "alternativas": {"A": "Certo, porque não tem fiscalização.", "B": "Errado. Em estrada (não pavimentada) a máxima é 60 km/h.", "C": "Certo, se não tiver curva.", "D": "Certo, se for de dia."}, "resposta": "B", "comentario": "Art. 61, §1º inciso II, alínea 'c' do CTB."},
    {"modulo": "1", "numero": "10", "questao": "Em um cruzamento com semáforo apagado, o que fazer?", "alternativas": {"A": "Avançar normalmente.", "B": "Parar apenas se quiser.", "C": "Reduzir a velocidade e utilizar a regra da direita", "D": "Acelerar para passar antes."}, "resposta": "C", "comentario": "Deve-se aplicar as normas gerais de preferência."},
    {"modulo": "1", "numero": "11", "questao": "Faixa de pedestre elevada serve para:", "alternativas": {"A": "Enfeitar a rua sem função prática.", "B": "Servir de estacionamento temporário.", "C": "Forçar redução de velocidade e dar prioridade segura ao pedestre.", "D": "Facilitar ultrapassagens."}, "resposta": "C", "comentario": "Dispositivo físico de acalmamento de tráfego."},
    {"modulo": "1", "numero": "12", "questao": "A presença de uma faixa de pedestres exige do motorista:", "alternativas": {"A": "Acelerar para liberar logo a via.", "B": "Tocar buzina para o pedestre correr.", "C": "Virar o volante sobre a faixa.", "D": "Parar e dar preferência ao pedestre."}, "resposta": "D", "comentario": "Prioridade máxima ao pedestre."},
    {"modulo": "1", "numero": "13", "questao": "Faixa exclusiva de ônibus (horário válido):", "alternativas": {"A": "Pode ser usada para adiantar a viagem.", "B": "Pode estacionar 'rapidinho'.", "C": "Não pode ser usada por carro, só cruzar para conversão onde permitido.", "D": "Pode trafegar à noite sempre."}, "resposta": "C", "comentario": "Exclusividade melhora o transporte coletivo e a segurança."},
    {"modulo": "1", "numero": "14", "questao": "Motociclista em semáforo deve parar:", "alternativas": {"A": "No meio dos carros.", "B": "No bolsão de motos, se existir, ou atrás da faixa de pedestres.", "C": "Depois da faixa de pedestres, já na esquina.", "D": "Em cima da faixa de pedestres"}, "resposta": "B", "comentario": "O bolsão é espaço seguro, caso não exista, respeita-se a faixa."},
    {"modulo": "1", "numero": "15", "questao": "Como os veículos são identificados formalmente?", "alternativas": {"A": "Com cores que o proprietário escolhe.", "B": "Com enfeites ou adesivos colocados pelo condutor.", "C": "São identificados por meio de placas externas dianteiras e traseiras, com letras e números.", "D": "O condutor coloca cada roda de uma cor."}, "resposta": "C", "comentario": "A identificação de veículos por placas está prevista no art. 115 do CTB."},
    {"modulo": "1", "numero": "16", "questao": "Por que o motociclista deve sinalizar antes de virar para direita ou para a esquerda?", "alternativas": {"A": "Só por educação.", "B": "Para avisar aos outros a sua intenção e evitar colisões.", "C": "Para evitar multa apenas.", "D": "Para chamar atenção."}, "resposta": "B", "comentario": "A sinalização é um ato de segurança, não apenas obrigação."},
    {"modulo": "1", "numero": "17", "questao": "Quais veículos têm apenas placa traseira?", "alternativas": {"A": "Todos os carros de passeio.", "B": "Somente ônibus.", "C": "Apenas caminhões.", "D": "Motocicletas e motonetas."}, "resposta": "D", "comentario": "De acordo com o art. 115, § 6º do CTB"},
    {"modulo": "1", "numero": "18", "questao": "Qual é a função das faixas da esquerda em uma via de várias faixas?", "alternativas": {"A": "Para caminhões e ônibus.", "B": "Para veículos lentos.", "C": "Serve para ultrapassagem e para veículos mais rápidos.", "D": "Para estacionar."}, "resposta": "C", "comentario": "Isso mantém o fluxo seguro e organizado."},
    {"modulo": "1", "numero": "19", "questao": "Quando há obras na via e sinalização provisória para acesso a imóveis, o condutor deve:", "alternativas": {"A": "Forçar a passagem.", "B": "Ignorar as barreiras.", "C": "Seguir as orientações dos agentes ou trabalhadores da obra.", "D": "Fazer manobra pela contramão."}, "resposta": "C", "comentario": "A sinalização provisória garante segurança durante intervenções."},
    {"modulo": "1", "numero": "20", "questao": "Aproximação de rotatória sem placa de pare nem semáforo. O que fazer?", "alternativas": {"A": "Entrar acelerando porque não tem placa.", "B": "Reduzir, observar e dar passagem a quem já circula dentro.", "C": "Parar dentro da rotatória para decidir a saída.", "D": "Parar o veículo completamente."}, "resposta": "B", "comentario": "Preferência interna é a regra. Art. 29, inciso III, alínea b do CTB"},
    {"modulo": "1", "numero": "21", "questao": "Como se classifica uma pista urbana e elevada, com acesso controlado, sem cruzamentos, com placas de 80 km/h?", "alternativas": {"A": "Via coletora.", "B": "Via local.", "C": "Via de trânsito rápido.", "D": "Estrada."}, "resposta": "C", "comentario": "A classificação de vias encontra-se no anexo do CTB."},
    {"modulo": "1", "numero": "22", "questao": "Você está em uma via coletora (40 km/h) e vê placa uma 30 km/h. Qual conduta o motorista deve adotar?", "alternativas": {"A": "Manter 40 km/h da coletora.", "B": "Seguir na velocidade que entender melhor.", "C": "Obedecer o limite de 30 km/h, pois sinalização específica prevalece.", "D": "Ignorar porque é temporária."}, "resposta": "C", "comentario": "Placa vigente regula a via naquele trecho."},
    {"modulo": "1", "numero": "23", "questao": "Em certa rotatória há placas dando preferência a quem se aproxima. Qual é a regra que vale?", "alternativas": {"A": "Vale a regra geral sempre.", "B": "Vale quem buzina.", "C": "Vale a sinalização do local, pois essa prevalece.", "D": "Vale quem está mais rápido."}, "resposta": "C", "comentario": "Sinalização pode alterar a preferência local."},
    {"modulo": "1", "numero": "24", "questao": "Quando o semáforo passa para a cor amarela, o que um condutor consciente deve fazer?", "alternativas": {"A": "Acelerar para aproveitar o sinal.", "B": "Parar bruscamente no meio da via.", "C": "Reduzir a velocidade e preparar-se para parar.", "D": "Buzinar para os pedestres atravessarem rápido."}, "resposta": "C", "comentario": "A interpretação correta do sinal é uma ação cognitiva essencial."},
    {"modulo": "1", "numero": "25", "questao": "Qual a conduta a ser adotada quando ver uma escola e alunos na calçada?", "alternativas": {"A": "Seguir no limite da via sem reduzir.", "B": "Reduzir bem a velocidade e ficar atento a travessias.", "C": "Buzinar para avisar.", "D": "Acelerar para passar rápido."}, "resposta": "B", "comentario": "Devem ser respeitadas as sinalizações de trânsito e as áreas de segurança."},
    {"modulo": "1", "numero": "26", "questao": "No contexto da sinalização horizontal de estacionamentos, o que a cor azul (faixa azul) das vagas representa?", "alternativas": {"A": "Vaga rotativa.", "B": "Vaga para idosos.", "C": "Vaga destinada a pessoas com deficiência.", "D": "Vaga para carga e descarga."}, "resposta": "C", "comentario": "O símbolo azul identifica vagas PCD."},
    {"modulo": "1", "numero": "27", "questao": "Um motorista vê uma placa de curva perigosa. O que deve fazer?", "alternativas": {"A": "Frear bruscamente no meio da curva.", "B": "Reduzir a velocidade e manter controle do veículo.", "C": "Acelerar para sair logo.", "D": "Ignorar a sinalização."}, "resposta": "B", "comentario": "A placa de 'Curva Perigosa' é uma advertência da condição adversa da via."},
    {"modulo": "1", "numero": "28", "questao": "Um motorista, dirigindo em excesso de velocidade, vê uma placa de curva perigosa e continua na mesma velocidade. Qual o risco?", "alternativas": {"A": "Melhorar o tempo de viagem.", "B": "Reduzir o consumo de combustível.", "C": "Perder o controle e causar um sinistro.", "D": "Evitar filas."}, "resposta": "C", "comentario": "A Direção Defensiva exige que o motorista reduza a velocidade."},
    {"modulo": "1", "numero": "29", "questao": "Carlos estaciona seu veículo de passeio em uma vaga com a placa contendo o texto 'Exceto Carga e Descarga – 30 min'. Ele pode permanecer ali com o veículo?", "alternativas": {"A": "Não, pois a vaga é exclusiva para veículos de carga por até 30 minutos.", "B": "Sim, se não houver caminhões.", "C": "Sim, por menos de 10 minutos.", "D": "Sim, desde que com pisca-alerta ligado."}, "resposta": "A", "comentario": "A sinalização vertical restringe o uso da vaga."},
    {"modulo": "1", "numero": "30", "questao": "Um condutor vê a placa 'Proibido' junto a outra com o texto 'Exceto veículos de emergência'. O que isso significa?", "alternativas": {"A": "Todos os veículos estão liberados.", "B": "Somente ônibus podem passar.", "C": "A restrição não se aplica a veículos de emergência, como ambulâncias, em serviço.", "D": "É uma placa de advertência."}, "resposta": "C", "comentario": "A placa adicional estabelece uma exceção à regra geral de proibição."},
    {"modulo": "1", "numero": "31", "questao": "Cláudia está de moto e vê uma placa de proibido veículos. Ela pode seguir?", "alternativas": {"A": "Sim, pois vale apenas para carros.", "B": "Sim, se estiver em baixa velocidade.", "C": "Não, pois motocicletas também são veículos automotores.", "D": "Apenas se for moradora da rua."}, "resposta": "C", "comentario": "A proibição se aplica a todos os veículos automotores, incluindo motocicletas."},
    {"modulo": "1", "numero": "32", "questao": "Em curvas indicadas por uma placa de curva, por que é importante olhar para o ponto de saída da curva?", "alternativas": {"A": "Para orientar o traçado da direção e manter a trajetória estável.", "B": "Para observar o retrovisor direito.", "C": "Para reduzir o consumo de combustível.", "D": "Para verificar o velocímetro."}, "resposta": "A", "comentario": "Antecipar o olhar ajuda a guiar o veículo com suavidade e segurança."},
    {"modulo": "1", "numero": "33", "questao": "Felipe segue pela faixa da direita e encontra placa de proibido mudar de faixa, seguida de 'Fim da proibição de mudar de faixa'. O que isso significa?", "alternativas": {"A": "Que a proibição vale até o fim da via.", "B": "Que a manobra continua proibida.", "C": "Que ele pode mudar de faixa a partir da segunda placa.", "D": "Que só motos podem mudar de faixa."}, "resposta": "C", "comentario": "A placa de 'fim de proibição' define o ponto exato onde a manobra volta a ser permitida."},
    {"modulo": "1", "numero": "34", "questao": "Júlia conduz um ônibus e encontra placa de proibido retorno próxima a uma rotatória. Qual é o comportamento correto?", "alternativas": {"A": "Fazer o retorno antes da rotatória.", "B": "Parar sobre a via.", "C": "Seguir em frente e utilizar a rotatória para mudar de sentido.", "D": "Encostar no acostamento e manobrar."}, "resposta": "C", "comentario": "A rotatória é o ponto adequado para retornar, respeitando a proibição localizada."},
    {"modulo": "1", "numero": "35", "questao": "O formato circular com borda vermelha da placa indica:", "alternativas": {"A": "Uma informação turística.", "B": "Uma proibição expressa ao condutor.", "C": "Uma advertência temporária.", "D": "Um serviço de utilidade pública."}, "resposta": "B", "comentario": "As placas circulares de fundo branco e borda vermelha pertencem à classe de regulamentação."},
    {"modulo": "1", "numero": "36", "questao": "A placa com formato triangular invertido tem como função:", "alternativas": {"A": "Diferenciar as placas de informação turística.", "B": "Facilitar o reconhecimento mesmo à distância e indicar atenção.", "C": "Servir apenas para fins estéticos.", "D": "Indicar uma área de estacionamento."}, "resposta": "B", "comentario": "O triângulo invertido é símbolo internacional de advertência."},
    {"modulo": "1", "numero": "37", "questao": "O que acontece se o condutor ignorar a placa PARE e não parar onde for obrigado?", "alternativas": {"A": "Ele será apenas advertido verbalmente.", "B": "Não acontece nada.", "C": "Ele comete infração gravíssima.", "D": "O veículo é removido imediatamente."}, "resposta": "C", "comentario": "Deixar de parar diante da placa PARE é infração gravíssima (CTB art. 208)."},
    {"modulo": "1", "numero": "38", "questao": "O que a placa de pista irregular está avisando?", "alternativas": {"A": "Que há um quebra-molas.", "B": "Que a pista é nova e lisa.", "C": "Que a pista tem irregularidades no pavimento.", "D": "Que há obras à frente."}, "resposta": "C", "comentario": "A placa alerta sobre buracos, remendos ou deformações na via."},
    {"modulo": "1", "numero": "39", "questao": "O que indica a placa Cruz de Santo André?", "alternativas": {"A": "Uma ponte sobre o rio.", "B": "O início de uma passagem de nível, onde a pista cruza com uma linha de trem.", "C": "Um cruzamento entre duas vias urbanas.", "D": "Um local de pedágio."}, "resposta": "B", "comentario": "A placa alerta que o motorista está prestes a cruzar trilhos ferroviários."},
    {"modulo": "1", "numero": "40", "questao": "O que indica a placa de rotatória com setas circulares?", "alternativas": {"A": "O ponto de parada obrigatória.", "B": "O sentido obrigatório de circulação na rotatória - anti-horário.", "C": "A entrada proibida na via.", "D": "A preferência de pedestres."}, "resposta": "B", "comentario": "O símbolo de setas circulares indica o sentido único que todos os veículos devem seguir na rotatória."},
    {"modulo": "1", "numero": "41", "questao": "O que indica a placa triangular com símbolo de rotatória?", "alternativas": {"A": "Que a via é de mão dupla.", "B": "Que a pista é de mão dupla.", "C": "Que há uma rotatória à frente.", "D": "Que é obrigatório parar."}, "resposta": "C", "comentario": "A placa adverte que o condutor se aproxima de uma interseção circular (rotatória)."},
    {"modulo": "1", "numero": "42", "questao": "O que o motorista deve fazer ao ver a placa de declive acentuado?", "alternativas": {"A": "Acelerar para descer mais rápido.", "B": "Ligar o pisca-alerta.", "C": "Reduzir a velocidade e usar freio motor.", "D": "Frear só quando o carro já estiver em alta velocidade."}, "resposta": "C", "comentario": "A redução de velocidade antes da descida garante segurança e controle do veículo."},
    {"modulo": "1", "numero": "43", "questao": "Qual o significado da placa de máquinas agrícolas?", "alternativas": {"A": "Indica que o condutor deve ultrapassar sempre que possível.", "B": "Indica que o condutor deve ignorar o aviso e seguir em alta velocidade.", "C": "Indica a presença ou o cruzamento de máquinas agrícolas na pista.", "D": "Indica que o condutor deve ultrapassar pelo acostamento."}, "resposta": "C", "comentario": "Indica a presença ou o cruzamento de máquinas agrícolas na pista."},
    {"modulo": "1", "numero": "44", "questao": "Por que a placa de sentido obrigatório é importante em vias urbanas com semáforo?", "alternativas": {"A": "Porque indica estacionamento permitido.", "B": "Porque dispensa o uso da seta.", "C": "Porque ajuda a definir fluxos compatíveis com o tempo semafórico.", "D": "Porque reduz a visibilidade."}, "resposta": "C", "comentario": "Garante harmonia entre sinalização vertical e semafórica, evitando conflitos."},
    {"modulo": "1", "numero": "45", "questao": "Qual é a diferença entre a placa de curva suave e curva acentuada?", "alternativas": {"A": "A curva suave indica uma curva muito mais fechada.", "B": "A curva suave indica uma curva menos acentuada.", "C": "A curva suave proíbe o tráfego de caminhões.", "D": "A curva suave é usada apenas em rotatórias."}, "resposta": "B", "comentario": "A-2a é usada para curvas suaves e a A-1a, para curvas acentuadas."},
    {"modulo": "1", "numero": "46", "questao": "Qual é a diferença entre a placa 'Trânsito de pedestres' e a placa 'Passagem sinalizada de pedestres'?", "alternativas": {"A": "Ambas têm o mesmo significado.", "B": "A primeira indica o trânsito frequente de pedestres, enquanto a segunda indica a presença de faixa de pedestres sinalizada.", "C": "A primeira é obrigatória e a segunda é proibitiva.", "D": "A placa indica travessia de ciclistas."}, "resposta": "B", "comentario": "A diferença está na representação da faixa no pictograma."},
    {"modulo": "1", "numero": "47", "questao": "Qual é o principal motivo de sinistros em locais com junções sucessivas contrárias?", "alternativas": {"A": "Falta de atenção do motorista que não percebe os veículos entrando ou cruzando.", "B": "A distração é a causa mais comum de colisões laterais nesses pontos.", "C": "Defeito no veículo.", "D": "Falta de acostamento."}, "resposta": "B", "comentario": "A distração é a causa mais comum de colisões laterais nesses pontos."},
    {"modulo": "1", "numero": "48", "questao": "Qual o principal erro que causa sinistro em cruzamentos?", "alternativas": {"A": "Usar o cinto de segurança.", "B": "Falta de atenção e avanço sem observar os outros veículos.", "C": "Manter velocidade reduzida.", "D": "Parar para observar o trânsito."}, "resposta": "B", "comentario": "A distração e o avanço apressado são causas comuns de colisão lateral."},
    {"modulo": "1", "numero": "49", "questao": "Qual o principal objetivo da restrição de veículos pesados em certas vias?", "alternativas": {"A": "Reduzir a velocidade dos ônibus nas rodovias.", "B": "Aumentar a segurança e preservar o fluxo adequado de veículos leves.", "C": "Induzir o uso de veículos particulares.", "D": "Garantir estacionamento público."}, "resposta": "B", "comentario": "A restrição evita congestionamentos e riscos estruturais."},
    {"modulo": "1", "numero": "50", "questao": "Se a via deixa de ser duplicada e surge placa de mão dupla, o que isso significa para o condutor?", "alternativas": {"A": "Que a via passa a ser exclusiva para ônibus.", "B": "Que haverá tráfego nos dois sentidos em um mesmo pavimento.", "C": "Que deve parar o veículo.", "D": "Que o limite de velocidade aumenta."}, "resposta": "B", "comentario": "Essa sinalização marca o fim da separação física de pistas."},
]

# Module 2 - Escolhas e Consequências (171 questions)
MODULO_2_QUESTIONS = [
    {"modulo": "2", "numero": "1", "questao": "Cassação da CNH ocorre, por exemplo, quando:", "alternativas": {"A": "O condutor dirige com o direito de dirigir suspenso ou reincide em determinadas infrações.", "B": "O condutor esquece de renovar a CNH dentro do prazo.", "C": "O condutor comete uma infração leve durante o período de suspensão.", "D": "O condutor acumula 20 pontos na CNH em um período de 12 meses."}, "resposta": "A", "comentario": "Conforme o art. 263, incisos I e II, do CTB."},
    {"modulo": "2", "numero": "2", "questao": "Qual a classificação de infração por dirigir sem possuir habilitação?", "alternativas": {"A": "Gravíssima.", "B": "Leve.", "C": "Média.", "D": "Só advertência."}, "resposta": "A", "comentario": "Tipificação e medidas previstas no CTB."},
    {"modulo": "2", "numero": "3", "questao": "Caso o comprador de um veículo não realize a transferência obrigatória, caberá ao vendedor:", "alternativas": {"A": "Comunicar a venda ao Detran, senão continua responsável por infrações e tributos.", "B": "Guardar o CRV e não falar nada.", "C": "Pagar o IPVA do novo dono.", "D": "Cancelar a placa."}, "resposta": "A", "comentario": "Art. 134 do CTB."},
    {"modulo": "2", "numero": "4", "questao": "É permitido transportar uma criança no colo, mesmo em trajeto curto?", "alternativas": {"A": "Não, isso configura uma infração de trânsito.", "B": "Não, porque ela se distrai facilmente.", "C": "Não, porque pode sujar o banco.", "D": "Não, porque o cinto fica frouxo."}, "resposta": "A", "comentario": "Art. 168 do CTB."},
    {"modulo": "2", "numero": "5", "questao": "Quando cabe advertência por escrito?", "alternativas": {"A": "Infrações leves ou médias, punidas com multa e sem outra infração nos últimos 12 meses.", "B": "Só gravíssima.", "C": "Em qualquer infração.", "D": "Apenas com sinistro."}, "resposta": "A", "comentario": "Conforme dispõe o art. 267 do CTB."},
    {"modulo": "2", "numero": "6", "questao": "O que é infração de trânsito?", "alternativas": {"A": "Inobservância a qualquer preceito do CTB.", "B": "Qualquer ato que desagrada outro condutor.", "C": "Só bater o carro em sinistro.", "D": "Um aviso sem efeito legal."}, "resposta": "A", "comentario": "Infração é violação expressa em lei."},
    {"modulo": "2", "numero": "7", "questao": "Por que as infrações gravíssimas podem ter multa multiplicada?", "alternativas": {"A": "Pelo alto potencial de dano à vida e à coletividade.", "B": "Para arrecadar mais.", "C": "Porque são raras.", "D": "Para punir só quem é reincidente."}, "resposta": "A", "comentario": "Refletem a gravidade da infração."},
    {"modulo": "2", "numero": "8", "questao": "Qual é o comportamento mais seguro ao dirigir perto de ciclistas?", "alternativas": {"A": "Reduzir a velocidade e manter uma distância mínima de 1,5 metro ao ultrapassar.", "B": "Acelerar para ultrapassar rapidamente.", "C": "Buzinar para o ciclista sair.", "D": "Passar bem perto do ciclista."}, "resposta": "A", "comentario": "Art. 201 do CTB."},
    {"modulo": "2", "numero": "9", "questao": "Usar o celular ao volante é:", "alternativas": {"A": "Um risco porque distrai o condutor e reduz o tempo de reação.", "B": "Uma ferramenta boa.", "C": "Uma ferramenta que ajuda a manter a calma.", "D": "Permitido em ruas pouco movimentadas."}, "resposta": "A", "comentario": "Distração por celular é uma das principais causas de sinistros."},
    {"modulo": "2", "numero": "10", "questao": "Qual a ideia da tolerância zero para álcool?", "alternativas": {"A": "Qualquer quantidade de álcool influencia na coordenação do condutor.", "B": "Que uma taça é liberada.", "C": "Que só vale para rodovia.", "D": "Que depende do humor do agente."}, "resposta": "A", "comentario": "O álcool compromete a coordenação do condutor."},
    {"modulo": "2", "numero": "11", "questao": "Ultrapassar pela contramão em local proibido é infração de qual natureza?", "alternativas": {"A": "Gravíssima.", "B": "Leve.", "C": "Média.", "D": "Grave."}, "resposta": "A", "comentario": "Art. 191 do CTB."},
    {"modulo": "2", "numero": "12", "questao": "O que acontece se o condutor recusar o teste do bafômetro?", "alternativas": {"A": "É considerado infrator, equiparado ao condutor alcoolizado.", "B": "Nada acontece.", "C": "Recebe apenas advertência verbal.", "D": "Deve fazer exame de sangue obrigatório."}, "resposta": "A", "comentario": "Art. 165-A do CTB."},
    {"modulo": "2", "numero": "13", "questao": "Dirigir sob efeito de substâncias psicoativas é:", "alternativas": {"A": "Infração gravíssima com penalidades severas.", "B": "Permitido se for medicamento.", "C": "Infração média.", "D": "Liberado em vias locais."}, "resposta": "A", "comentario": "Art. 165 do CTB."},
    {"modulo": "2", "numero": "14", "questao": "Participar de rachas ou competições não autorizadas em via pública:", "alternativas": {"A": "É crime de trânsito.", "B": "É apenas infração administrativa.", "C": "É permitido em horários noturnos.", "D": "Não tem penalidade."}, "resposta": "A", "comentario": "Art. 308 do CTB."},
    {"modulo": "2", "numero": "15", "questao": "Deixar de prestar socorro à vítima de acidente de trânsito:", "alternativas": {"A": "É crime de trânsito.", "B": "É infração leve.", "C": "Não tem consequência legal.", "D": "É apenas falta de educação."}, "resposta": "A", "comentario": "Art. 304 do CTB."},
    {"modulo": "2", "numero": "16", "questao": "A penalidade de suspensão do direito de dirigir pode variar de:", "alternativas": {"A": "2 meses a 5 anos.", "B": "1 semana a 1 mês.", "C": "6 meses a 1 ano.", "D": "Apenas 30 dias."}, "resposta": "A", "comentario": "Art. 261 do CTB."},
    {"modulo": "2", "numero": "17", "questao": "Quantos pontos acumulados em 12 meses podem resultar em suspensão da CNH para condutor profissional?", "alternativas": {"A": "40 pontos.", "B": "20 pontos.", "C": "10 pontos.", "D": "30 pontos."}, "resposta": "A", "comentario": "Lei 14.071/2020."},
    {"modulo": "2", "numero": "18", "questao": "O condutor que comete homicídio culposo na direção de veículo automotor:", "alternativas": {"A": "Responde criminalmente com pena de detenção.", "B": "Paga apenas multa.", "C": "Não é responsabilizado.", "D": "Recebe apenas advertência."}, "resposta": "A", "comentario": "Art. 302 do CTB."},
    {"modulo": "2", "numero": "19", "questao": "Conduzir veículo com CNH ou PPD cassada:", "alternativas": {"A": "É crime de trânsito.", "B": "É infração média.", "C": "Não tem punição.", "D": "É infração leve."}, "resposta": "A", "comentario": "Art. 309 do CTB."},
    {"modulo": "2", "numero": "20", "questao": "Estacionar em vaga para deficientes sem credencial:", "alternativas": {"A": "É infração gravíssima.", "B": "É infração leve.", "C": "É permitido por até 5 minutos.", "D": "É infração média."}, "resposta": "A", "comentario": "Art. 181, inciso XX do CTB."},
]

# Module 3 - Na Direção da Segurança (575 questions)
MODULO_3_QUESTIONS = [
    {"modulo": "3", "numero": "1", "questao": "Ao ultrapassar ônibus, qual a conduta segura:", "alternativas": {"A": "Ultrapassar com espaço e tempo suficientes e só voltar ao ver o ônibus inteiro no retrovisor.", "B": "Voltar logo após ultrapassar a parte dianteira do ônibus.", "C": "Voltar antes de terminar a ultrapassagem.", "D": "Passar colado para acabar rápido."}, "resposta": "A", "comentario": "Pontos cegos grandes exigem distância e visibilidade."},
    {"modulo": "3", "numero": "2", "questao": "Ao ultrapassar um ciclista, o motociclista deve:", "alternativas": {"A": "Reduzir a velocidade e manter 1,5 metro de distância lateral.", "B": "Acelerar para sair logo.", "C": "Passar colado para economizar espaço.", "D": "Buzinar alto para avisar."}, "resposta": "A", "comentario": "Arts. 201 e 220, inciso XIII do CTB."},
    {"modulo": "3", "numero": "3", "questao": "De acordo com o CTB, os ciclomotores podem trafegar em rodovias ou vias de trânsito rápido?", "alternativas": {"A": "Não, é proibida a circulação de ciclomotores em vias de trânsito rápido.", "B": "Sim, se andar devagar.", "C": "Sim, se for domingo.", "D": "Sim, se usar colete refletivo."}, "resposta": "A", "comentario": "Art. 57 do CTB."},
    {"modulo": "3", "numero": "4", "questao": "Em cruzamento sem sinalização, quem tem a preferência?", "alternativas": {"A": "Quem vem pela direita.", "B": "Quem vem pela esquerda.", "C": "O veículo maior.", "D": "O que buzinar primeiro."}, "resposta": "A", "comentario": "Regra da direita, art. 29, inciso III, alínea c do CTB."},
    {"modulo": "3", "numero": "5", "questao": "Locais onde a ultrapassagem é proibida?", "alternativas": {"A": "Curvas, aclives sem visibilidade, passagens de nível, pontes/viadutos e faixas de pedestres.", "B": "Só em rodovia.", "C": "Apenas à noite.", "D": "Em dias de chuva somente."}, "resposta": "A", "comentario": "Pontos críticos com baixa visibilidade e alto risco."},
    {"modulo": "3", "numero": "6", "questao": "O que determina o CTB sobre proteção aos mais frágeis?", "alternativas": {"A": "Veículos maiores devem cuidar dos menores, motorizados protegem não motorizados.", "B": "Cada um por si.", "C": "Pedestres devem sempre sair da frente.", "D": "Carros têm prioridade em qualquer situação."}, "resposta": "A", "comentario": "Hierarquia de proteção no trânsito, conforme art. 29, §2º."},
    {"modulo": "3", "numero": "7", "questao": "Ultrapassar em curvas é permitido?", "alternativas": {"A": "Não, pois há risco de colisão frontal.", "B": "Sim, desde que o motorista saiba dirigir bem.", "C": "Sim, se o carro for potente.", "D": "Apenas à noite."}, "resposta": "A", "comentario": "Locais sem visibilidade proíbem ultrapassagem."},
    {"modulo": "3", "numero": "8", "questao": "O que significa o termo via?", "alternativas": {"A": "É todo o espaço de circulação: pista, calçada, acostamento, canteiro.", "B": "É somente a pista de asfalto.", "C": "É só a parte do pedestre.", "D": "É só a rua da sua casa."}, "resposta": "A", "comentario": "Definição do Glossário do CTB."},
    {"modulo": "3", "numero": "9", "questao": "A CNH é um documento de que tipo?", "alternativas": {"A": "Documento pessoal e intransferível, em versão física e digital, vale como identidade.", "B": "Documento que pode ser emprestado.", "C": "Documento que só vale no bairro.", "D": "Documento que serve apenas para comprar combustível."}, "resposta": "A", "comentario": "A CNH tem fé pública e é pessoal."},
    {"modulo": "3", "numero": "10", "questao": "Em uma rotatória, quem tem a preferência?", "alternativas": {"A": "Quem já está circulando dentro dela.", "B": "Quem está entrando.", "C": "O veículo maior.", "D": "O mais rápido."}, "resposta": "A", "comentario": "A prioridade é de quem já está na rotatória."},
    {"modulo": "3", "numero": "11", "questao": "Qual a distância mínima de seguimento em condições normais?", "alternativas": {"A": "Distância que permita parar com segurança em caso de frenagem brusca.", "B": "Menos de 1 metro.", "C": "Não existe distância mínima.", "D": "Apenas em rodovias."}, "resposta": "A", "comentario": "Art. 29, II do CTB."},
    {"modulo": "3", "numero": "12", "questao": "Em pista molhada, o condutor deve:", "alternativas": {"A": "Reduzir a velocidade e aumentar a distância do veículo da frente.", "B": "Manter a mesma velocidade.", "C": "Acelerar para passar logo.", "D": "Frear bruscamente."}, "resposta": "A", "comentario": "Condição adversa exige cautela redobrada."},
    {"modulo": "3", "numero": "13", "questao": "O que é aquaplanagem?", "alternativas": {"A": "Perda de contato dos pneus com o solo devido à água na pista.", "B": "Excesso de velocidade.", "C": "Falta de combustível.", "D": "Problema mecânico."}, "resposta": "A", "comentario": "Fenômeno perigoso em pistas molhadas."},
    {"modulo": "3", "numero": "14", "questao": "Dirigir com faróis desligados à noite:", "alternativas": {"A": "É infração gravíssima.", "B": "É permitido em vias iluminadas.", "C": "É infração leve.", "D": "Não tem problema."}, "resposta": "A", "comentario": "Art. 250 do CTB."},
    {"modulo": "3", "numero": "15", "questao": "Qual a velocidade máxima em vias locais urbanas?", "alternativas": {"A": "30 km/h.", "B": "40 km/h.", "C": "60 km/h.", "D": "80 km/h."}, "resposta": "A", "comentario": "Art. 61 do CTB."},
    {"modulo": "3", "numero": "16", "questao": "Ao entrar em um túnel durante o dia, o condutor deve:", "alternativas": {"A": "Acender os faróis.", "B": "Manter os faróis apagados.", "C": "Usar apenas luz de posição.", "D": "Buzinar para avisar."}, "resposta": "A", "comentario": "Art. 40 do CTB."},
    {"modulo": "3", "numero": "17", "questao": "O uso do cinto de segurança é obrigatório:", "alternativas": {"A": "Para todos os ocupantes do veículo.", "B": "Apenas para o motorista.", "C": "Apenas no banco da frente.", "D": "Apenas em rodovias."}, "resposta": "A", "comentario": "Art. 65 do CTB."},
    {"modulo": "3", "numero": "18", "questao": "Crianças até 10 anos devem ser transportadas:", "alternativas": {"A": "No banco traseiro com dispositivo de retenção adequado.", "B": "No banco da frente.", "C": "No colo de um adulto.", "D": "Em qualquer posição."}, "resposta": "A", "comentario": "Art. 64 do CTB."},
    {"modulo": "3", "numero": "19", "questao": "Qual equipamento é obrigatório para motociclistas?", "alternativas": {"A": "Capacete com viseira ou óculos de proteção.", "B": "Apenas colete.", "C": "Luvas somente.", "D": "Nenhum equipamento."}, "resposta": "A", "comentario": "Art. 54 do CTB."},
    {"modulo": "3", "numero": "20", "questao": "O que fazer antes de iniciar uma ultrapassagem?", "alternativas": {"A": "Verificar espelhos, sinalizar e certificar-se de que há espaço seguro.", "B": "Apenas buzinar.", "C": "Acelerar sem olhar.", "D": "Piscar farol alto."}, "resposta": "A", "comentario": "Art. 29, X do CTB."},
]

# Module 4 - Cuidar, Agir e Preservar (36 questions)
MODULO_4_QUESTIONS = [
    {"modulo": "4", "numero": "1", "questao": "O que um condutor recém-habilitado com a Categoria A está autorizado a pilotar?", "alternativas": {"A": "Motocicletas, motonetas e ciclomotores.", "B": "Qualquer tipo de motocicleta, exceto triciclos.", "C": "Apenas motocicletas de até 50 cilindradas.", "D": "Veículos de duas rodas e picapes leves."}, "resposta": "A", "comentario": "Esta categoria abrange todos os veículos motorizados de duas ou três rodas."},
    {"modulo": "4", "numero": "2", "questao": "Sobre o uso de capacete danificado ou que já sofreu um impacto, o que deve ser feito?", "alternativas": {"A": "Nunca deve ser utilizado, pois sua eficácia está comprometida.", "B": "Deve ser consertado em um local especializado.", "C": "Pode ser emprestado.", "D": "Pode ser usado em trajetos curtos."}, "resposta": "A", "comentario": "Um capacete que sofreu impacto pode ter danos estruturais não visíveis."},
    {"modulo": "4", "numero": "3", "questao": "Ao ligar para um número de emergência como o SAMU (192), qual informação é mais crucial?", "alternativas": {"A": "A localização exata do sinistro e o número de vítimas.", "B": "O seu nome completo e número de telefone.", "C": "Quem foi o culpado pela colisão.", "D": "O modelo e a cor dos veículos."}, "resposta": "A", "comentario": "Saber onde ir e quantos recursos enviar é a informação mais crítica."},
    {"modulo": "4", "numero": "4", "questao": "Ao presenciar um sinistro, você vê um motociclista caído. Qual ação é um erro grave?", "alternativas": {"A": "Tentar remover o capacete do motociclista para ajudá-lo a respirar melhor.", "B": "Sinalizar o local com o triângulo de segurança.", "C": "Conversar com a vítima para acalmá-la.", "D": "Ligar para o número 193 (Bombeiros)."}, "resposta": "A", "comentario": "A retirada do capacete só deve ser feita por profissionais."},
    {"modulo": "4", "numero": "5", "questao": "Por que dirigir com sono é tão perigoso quanto dirigir alcoolizado?", "alternativas": {"A": "Porque a sonolência reduz os reflexos, a atenção e a capacidade de reação.", "B": "Apenas porque o sono causa bocejos.", "C": "Porque o sono só afeta a velocidade.", "D": "Apenas por causa da regra de 80 km/h."}, "resposta": "A", "comentario": "O efeito da sonolência no desempenho é equiparado ao do álcool."},
    {"modulo": "4", "numero": "6", "questao": "Qual é o objetivo da condução segura?", "alternativas": {"A": "Evitar sinistros e preservar vidas.", "B": "Chegar mais rápido ao destino.", "C": "Mostrar habilidade no volante.", "D": "Usar o freio o mínimo possível."}, "resposta": "A", "comentario": "A condução segura tem como foco a prevenção de sinistros."},
    {"modulo": "4", "numero": "7", "questao": "Qual a diferença entre direção defensiva e preventiva?", "alternativas": {"A": "Defensiva protege, preventiva antecipa o risco.", "B": "Defensiva evita multas, preventiva é opcional.", "C": "Defensiva é usada em rodovias, preventiva em cidades.", "D": "Não há diferença entre elas."}, "resposta": "A", "comentario": "A direção defensiva reage com segurança, a preventiva evita o perigo antes."},
    {"modulo": "4", "numero": "8", "questao": "Qual atitude evita derrapagens em curvas?", "alternativas": {"A": "Reduzir a velocidade antes da curva.", "B": "Frear bruscamente dentro da curva.", "C": "Acelerar forte na saída.", "D": "Girar o volante rapidamente."}, "resposta": "A", "comentario": "Redução antecipada mantém a aderência dos pneus."},
    {"modulo": "4", "numero": "9", "questao": "Qual afirmação sobre viagens curtas é correta?", "alternativas": {"A": "O cinto deve ser usado em todas as viagens.", "B": "Em trajetos curtos, o cinto é dispensável.", "C": "Só usar o cinto após 10 km.", "D": "Utilizar o cinto apenas à noite."}, "resposta": "A", "comentario": "Muitos sinistros ocorrem perto de casa."},
    {"modulo": "4", "numero": "10", "questao": "João estava dirigindo na cidade quando viu uma colisão grave. Qual número de emergência deve ligar para o SAMU?", "alternativas": {"A": "192", "B": "193", "C": "190", "D": "191"}, "resposta": "A", "comentario": "O SAMU é o número 192."},
    {"modulo": "4", "numero": "11", "questao": "Quais são os elementos da direção defensiva?", "alternativas": {"A": "Conhecimento, atenção, previsão, habilidade e ação.", "B": "Velocidade, potência e freio.", "C": "Apenas atenção.", "D": "Somente habilidade."}, "resposta": "A", "comentario": "Os cinco elementos fundamentais da direção defensiva."},
    {"modulo": "4", "numero": "12", "questao": "O que fazer em caso de incêndio no veículo?", "alternativas": {"A": "Sair imediatamente do veículo e afastar-se.", "B": "Tentar apagar com água.", "C": "Continuar dirigindo.", "D": "Abrir o capô imediatamente."}, "resposta": "A", "comentario": "A segurança pessoal é prioridade."},
    {"modulo": "4", "numero": "13", "questao": "Qual o procedimento correto ao socorrer uma vítima inconsciente?", "alternativas": {"A": "Verificar sinais vitais e chamar socorro especializado.", "B": "Dar água para a vítima.", "C": "Movimentar a vítima.", "D": "Aplicar medicamentos."}, "resposta": "A", "comentario": "Não se deve mover a vítima sem treinamento adequado."},
    {"modulo": "4", "numero": "14", "questao": "O triângulo de sinalização deve ser colocado a que distância do veículo?", "alternativas": {"A": "Mínimo de 30 metros em vias urbanas.", "B": "1 metro do veículo.", "C": "Dentro do veículo.", "D": "Não é necessário usar."}, "resposta": "A", "comentario": "Permite que outros motoristas vejam o obstáculo a tempo."},
    {"modulo": "4", "numero": "15", "questao": "O que significa a sigla PAS nos primeiros socorros?", "alternativas": {"A": "Proteger, Avisar, Socorrer.", "B": "Parar, Aguardar, Sair.", "C": "Prevenir, Alertar, Salvar.", "D": "Primeiro, Atender, Socorro."}, "resposta": "A", "comentario": "Sequência básica de primeiros socorros."},
    {"modulo": "4", "numero": "16", "questao": "Qual é a função do freio ABS?", "alternativas": {"A": "Evitar o travamento das rodas durante a frenagem.", "B": "Aumentar a velocidade.", "C": "Diminuir o consumo.", "D": "Ligar o ar-condicionado."}, "resposta": "A", "comentario": "O ABS permite manter o controle direcional ao frear."},
    {"modulo": "4", "numero": "17", "questao": "Como prevenir a fadiga ao dirigir em viagens longas?", "alternativas": {"A": "Fazer pausas regulares a cada 2 horas.", "B": "Tomar muito café.", "C": "Dirigir mais rápido.", "D": "Não parar para descansar."}, "resposta": "A", "comentario": "Pausas regulares são essenciais para manter a atenção."},
    {"modulo": "4", "numero": "18", "questao": "O que é o ponto cego do veículo?", "alternativas": {"A": "Área ao redor do veículo que não é visível pelos espelhos.", "B": "Parte frontal do carro.", "C": "O painel do veículo.", "D": "O porta-malas."}, "resposta": "A", "comentario": "É importante virar a cabeça para verificar o ponto cego."},
    {"modulo": "4", "numero": "19", "questao": "Por que é importante manter os pneus calibrados?", "alternativas": {"A": "Para garantir estabilidade, economia de combustível e durabilidade.", "B": "Apenas por estética.", "C": "Não faz diferença.", "D": "Somente em viagens longas."}, "resposta": "A", "comentario": "Pneus mal calibrados afetam a segurança e o consumo."},
    {"modulo": "4", "numero": "20", "questao": "Qual é a principal causa de acidentes no trânsito brasileiro?", "alternativas": {"A": "Fator humano (imprudência, imperícia, negligência).", "B": "Condição das vias.", "C": "Falha mecânica.", "D": "Condições climáticas."}, "resposta": "A", "comentario": "A maioria dos acidentes é causada por erro humano."},
]

# Combine all questions
ALL_QUESTIONS = MODULO_1_QUESTIONS + MODULO_2_QUESTIONS + MODULO_3_QUESTIONS + MODULO_4_QUESTIONS

async def populate_database():
    """Populate the database with all questions"""
    mongo_url = os.environ.get('MONGO_URL')
    db_name = os.environ.get('DB_NAME', 'detran_quiz')
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    questions_collection = db.questions
    
    # Clear existing questions
    print("Clearing existing questions...")
    await questions_collection.delete_many({})
    print("Cleared existing questions.")
    
    # Insert questions
    print(f"Inserting {len(ALL_QUESTIONS)} questions...")
    questions_to_insert = []
    for q in ALL_QUESTIONS:
        question_doc = {
            "_id": str(uuid.uuid4()),
            "modulo": q["modulo"],
            "numero": q["numero"],
            "questao": q["questao"],
            "alternativas": q["alternativas"],
            "resposta": q["resposta"],
            "comentario": q["comentario"],
            "has_image": False,
            "image_placeholder": None
        }
        questions_to_insert.append(question_doc)
    
    if questions_to_insert:
        await questions_collection.insert_many(questions_to_insert)
        print(f"Successfully inserted {len(questions_to_insert)} questions!")
    
    # Print summary
    print("\n=== Database Summary ===")
    for modulo in ["1", "2", "3", "4"]:
        count = await questions_collection.count_documents({"modulo": modulo})
        print(f"Module {modulo}: {count} questions")
    
    total = await questions_collection.count_documents({})
    print(f"\nTotal questions: {total}")
    
    client.close()

if __name__ == "__main__":
    asyncio.run(populate_database())
